package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * FDspselc generated by hbm2java
 */
@Entity
@Table(name = "F_DSPSELC", schema = "DB2ADMIN")
public class FDspselc implements java.io.Serializable {

	private FDspselcId id;
	private Character item1;
	private Character item2;
	private Character item3;
	private Character item4;
	private Character item5;
	private Character item6;
	private Character item7;
	private Character item8;
	private Character item9;
	private Character item10;
	private Character item11;
	private Character item12;
	private Character item13;
	private Character item14;
	private Character item15;
	private Character item16;
	private Character item17;
	private Character item18;
	private Character item19;
	private Character item20;
	private Character item21;
	private Character item22;
	private Character item23;
	private Character item24;
	private Character item25;
	private Character item26;
	private Character item27;
	private Character item28;
	private Character item29;
	private Character item30;
	private Character item31;
	private Character item32;
	private Character item33;
	private Character item34;
	private Character item35;
	private Character item36;
	private Character item37;
	private Character item38;
	private Character item39;
	private Character item40;
	private Character item41;
	private Character item42;
	private Character item43;
	private Character item44;
	private Character item45;
	private Character item46;
	private Character item47;
	private Character item48;
	private Character item49;
	private Character item50;
	private Character item51;
	private Character item52;
	private Character item53;
	private Character item54;
	private Character item55;
	private Character item56;
	private Character item57;
	private Character item58;
	private Character item59;
	private Character item60;
	private Character item61;
	private Character item62;
	private Character item63;
	private Character item64;
	private Character item65;
	private Character item66;
	private Character item67;
	private Character item68;
	private Character item69;
	private Character item70;
	private Character item71;
	private Character item72;
	private Character item73;
	private Character item74;
	private Character item75;
	private Character item76;
	private Character item77;
	private Character item78;
	private Character item79;
	private Character item80;
	private Character item81;
	private Character item82;
	private Character item83;
	private Character item84;
	private Character item85;
	private Character item86;
	private Character item87;
	private Character item88;
	private Character item89;
	private Character item90;
	private Character item91;
	private Character item92;
	private Character item93;
	private Character item94;
	private Character item95;
	private Character item96;
	private Character item97;
	private Character item98;
	private Character item99;
	private Character item100;
	private Character item101;
	private Character item102;
	private Character item103;
	private Character item104;
	private Character item105;
	private Character item106;
	private Character item107;
	private Character item108;
	private Character item109;
	private Character item110;
	private Character item111;
	private Character item112;
	private Character item113;
	private Character item114;
	private Character item115;
	private Character item116;
	private Character item117;
	private Character item118;
	private Character item119;
	private Character item120;
	private Character item121;
	private Character item122;
	private Character item123;
	private Character item124;
	private Character item125;
	private Character item126;
	private Character item127;
	private Character item128;
	private Character item129;
	private Character item130;
	private Character item131;
	private Character item132;
	private Character item133;
	private Character item134;
	private Character item135;
	private Character item136;
	private Character item137;
	private Character item138;
	private Character item139;
	private Character item140;
	private Character item141;
	private Character item142;
	private Character item143;
	private Character item144;
	private Character item145;
	private Character item146;
	private Character item147;
	private Character item148;
	private Character item149;
	private Character item150;
	private Character item151;
	private Character item152;
	private Character item153;
	private Character item154;
	private Character item155;
	private Character item156;
	private Character item157;
	private Character item158;
	private Character item159;
	private Character item160;
	private Character item161;
	private Character item162;
	private Character item163;
	private Character item164;
	private Character item165;
	private Character item166;
	private Character item167;
	private Character item168;
	private Character item169;
	private Character item170;
	private Character item171;
	private Character item172;
	private Character item173;
	private Character item174;
	private Character item175;
	private Character item176;
	private Character item177;
	private Character item178;
	private Character item179;
	private Character item180;
	private Character item181;
	private Character item182;
	private Character item183;
	private Character item184;
	private Character item185;
	private Character item186;
	private Character item187;
	private Character item188;
	private Character item189;
	private Character item190;
	private Character item191;
	private Character item192;
	private Character item193;
	private Character item194;
	private Character item195;
	private Character item196;
	private Character item197;
	private Character item198;
	private Character item199;
	private Character item200;

	public FDspselc() {
	}

	public FDspselc(FDspselcId id) {
		this.id = id;
	}

	public FDspselc(FDspselcId id, Character item1, Character item2,
			Character item3, Character item4, Character item5, Character item6,
			Character item7, Character item8, Character item9,
			Character item10, Character item11, Character item12,
			Character item13, Character item14, Character item15,
			Character item16, Character item17, Character item18,
			Character item19, Character item20, Character item21,
			Character item22, Character item23, Character item24,
			Character item25, Character item26, Character item27,
			Character item28, Character item29, Character item30,
			Character item31, Character item32, Character item33,
			Character item34, Character item35, Character item36,
			Character item37, Character item38, Character item39,
			Character item40, Character item41, Character item42,
			Character item43, Character item44, Character item45,
			Character item46, Character item47, Character item48,
			Character item49, Character item50, Character item51,
			Character item52, Character item53, Character item54,
			Character item55, Character item56, Character item57,
			Character item58, Character item59, Character item60,
			Character item61, Character item62, Character item63,
			Character item64, Character item65, Character item66,
			Character item67, Character item68, Character item69,
			Character item70, Character item71, Character item72,
			Character item73, Character item74, Character item75,
			Character item76, Character item77, Character item78,
			Character item79, Character item80, Character item81,
			Character item82, Character item83, Character item84,
			Character item85, Character item86, Character item87,
			Character item88, Character item89, Character item90,
			Character item91, Character item92, Character item93,
			Character item94, Character item95, Character item96,
			Character item97, Character item98, Character item99,
			Character item100, Character item101, Character item102,
			Character item103, Character item104, Character item105,
			Character item106, Character item107, Character item108,
			Character item109, Character item110, Character item111,
			Character item112, Character item113, Character item114,
			Character item115, Character item116, Character item117,
			Character item118, Character item119, Character item120,
			Character item121, Character item122, Character item123,
			Character item124, Character item125, Character item126,
			Character item127, Character item128, Character item129,
			Character item130, Character item131, Character item132,
			Character item133, Character item134, Character item135,
			Character item136, Character item137, Character item138,
			Character item139, Character item140, Character item141,
			Character item142, Character item143, Character item144,
			Character item145, Character item146, Character item147,
			Character item148, Character item149, Character item150,
			Character item151, Character item152, Character item153,
			Character item154, Character item155, Character item156,
			Character item157, Character item158, Character item159,
			Character item160, Character item161, Character item162,
			Character item163, Character item164, Character item165,
			Character item166, Character item167, Character item168,
			Character item169, Character item170, Character item171,
			Character item172, Character item173, Character item174,
			Character item175, Character item176, Character item177,
			Character item178, Character item179, Character item180,
			Character item181, Character item182, Character item183,
			Character item184, Character item185, Character item186,
			Character item187, Character item188, Character item189,
			Character item190, Character item191, Character item192,
			Character item193, Character item194, Character item195,
			Character item196, Character item197, Character item198,
			Character item199, Character item200) {
		this.id = id;
		this.item1 = item1;
		this.item2 = item2;
		this.item3 = item3;
		this.item4 = item4;
		this.item5 = item5;
		this.item6 = item6;
		this.item7 = item7;
		this.item8 = item8;
		this.item9 = item9;
		this.item10 = item10;
		this.item11 = item11;
		this.item12 = item12;
		this.item13 = item13;
		this.item14 = item14;
		this.item15 = item15;
		this.item16 = item16;
		this.item17 = item17;
		this.item18 = item18;
		this.item19 = item19;
		this.item20 = item20;
		this.item21 = item21;
		this.item22 = item22;
		this.item23 = item23;
		this.item24 = item24;
		this.item25 = item25;
		this.item26 = item26;
		this.item27 = item27;
		this.item28 = item28;
		this.item29 = item29;
		this.item30 = item30;
		this.item31 = item31;
		this.item32 = item32;
		this.item33 = item33;
		this.item34 = item34;
		this.item35 = item35;
		this.item36 = item36;
		this.item37 = item37;
		this.item38 = item38;
		this.item39 = item39;
		this.item40 = item40;
		this.item41 = item41;
		this.item42 = item42;
		this.item43 = item43;
		this.item44 = item44;
		this.item45 = item45;
		this.item46 = item46;
		this.item47 = item47;
		this.item48 = item48;
		this.item49 = item49;
		this.item50 = item50;
		this.item51 = item51;
		this.item52 = item52;
		this.item53 = item53;
		this.item54 = item54;
		this.item55 = item55;
		this.item56 = item56;
		this.item57 = item57;
		this.item58 = item58;
		this.item59 = item59;
		this.item60 = item60;
		this.item61 = item61;
		this.item62 = item62;
		this.item63 = item63;
		this.item64 = item64;
		this.item65 = item65;
		this.item66 = item66;
		this.item67 = item67;
		this.item68 = item68;
		this.item69 = item69;
		this.item70 = item70;
		this.item71 = item71;
		this.item72 = item72;
		this.item73 = item73;
		this.item74 = item74;
		this.item75 = item75;
		this.item76 = item76;
		this.item77 = item77;
		this.item78 = item78;
		this.item79 = item79;
		this.item80 = item80;
		this.item81 = item81;
		this.item82 = item82;
		this.item83 = item83;
		this.item84 = item84;
		this.item85 = item85;
		this.item86 = item86;
		this.item87 = item87;
		this.item88 = item88;
		this.item89 = item89;
		this.item90 = item90;
		this.item91 = item91;
		this.item92 = item92;
		this.item93 = item93;
		this.item94 = item94;
		this.item95 = item95;
		this.item96 = item96;
		this.item97 = item97;
		this.item98 = item98;
		this.item99 = item99;
		this.item100 = item100;
		this.item101 = item101;
		this.item102 = item102;
		this.item103 = item103;
		this.item104 = item104;
		this.item105 = item105;
		this.item106 = item106;
		this.item107 = item107;
		this.item108 = item108;
		this.item109 = item109;
		this.item110 = item110;
		this.item111 = item111;
		this.item112 = item112;
		this.item113 = item113;
		this.item114 = item114;
		this.item115 = item115;
		this.item116 = item116;
		this.item117 = item117;
		this.item118 = item118;
		this.item119 = item119;
		this.item120 = item120;
		this.item121 = item121;
		this.item122 = item122;
		this.item123 = item123;
		this.item124 = item124;
		this.item125 = item125;
		this.item126 = item126;
		this.item127 = item127;
		this.item128 = item128;
		this.item129 = item129;
		this.item130 = item130;
		this.item131 = item131;
		this.item132 = item132;
		this.item133 = item133;
		this.item134 = item134;
		this.item135 = item135;
		this.item136 = item136;
		this.item137 = item137;
		this.item138 = item138;
		this.item139 = item139;
		this.item140 = item140;
		this.item141 = item141;
		this.item142 = item142;
		this.item143 = item143;
		this.item144 = item144;
		this.item145 = item145;
		this.item146 = item146;
		this.item147 = item147;
		this.item148 = item148;
		this.item149 = item149;
		this.item150 = item150;
		this.item151 = item151;
		this.item152 = item152;
		this.item153 = item153;
		this.item154 = item154;
		this.item155 = item155;
		this.item156 = item156;
		this.item157 = item157;
		this.item158 = item158;
		this.item159 = item159;
		this.item160 = item160;
		this.item161 = item161;
		this.item162 = item162;
		this.item163 = item163;
		this.item164 = item164;
		this.item165 = item165;
		this.item166 = item166;
		this.item167 = item167;
		this.item168 = item168;
		this.item169 = item169;
		this.item170 = item170;
		this.item171 = item171;
		this.item172 = item172;
		this.item173 = item173;
		this.item174 = item174;
		this.item175 = item175;
		this.item176 = item176;
		this.item177 = item177;
		this.item178 = item178;
		this.item179 = item179;
		this.item180 = item180;
		this.item181 = item181;
		this.item182 = item182;
		this.item183 = item183;
		this.item184 = item184;
		this.item185 = item185;
		this.item186 = item186;
		this.item187 = item187;
		this.item188 = item188;
		this.item189 = item189;
		this.item190 = item190;
		this.item191 = item191;
		this.item192 = item192;
		this.item193 = item193;
		this.item194 = item194;
		this.item195 = item195;
		this.item196 = item196;
		this.item197 = item197;
		this.item198 = item198;
		this.item199 = item199;
		this.item200 = item200;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "menugrpCode", column = @Column(name = "MENUGRP_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "menuexeCode", column = @Column(name = "MENUEXE_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "userid", column = @Column(name = "USERID", nullable = false, length = 10)) })
	public FDspselcId getId() {
		return this.id;
	}

	public void setId(FDspselcId id) {
		this.id = id;
	}

	@Column(name = "ITEM1", length = 1)
	public Character getItem1() {
		return this.item1;
	}

	public void setItem1(Character item1) {
		this.item1 = item1;
	}

	@Column(name = "ITEM2", length = 1)
	public Character getItem2() {
		return this.item2;
	}

	public void setItem2(Character item2) {
		this.item2 = item2;
	}

	@Column(name = "ITEM3", length = 1)
	public Character getItem3() {
		return this.item3;
	}

	public void setItem3(Character item3) {
		this.item3 = item3;
	}

	@Column(name = "ITEM4", length = 1)
	public Character getItem4() {
		return this.item4;
	}

	public void setItem4(Character item4) {
		this.item4 = item4;
	}

	@Column(name = "ITEM5", length = 1)
	public Character getItem5() {
		return this.item5;
	}

	public void setItem5(Character item5) {
		this.item5 = item5;
	}

	@Column(name = "ITEM6", length = 1)
	public Character getItem6() {
		return this.item6;
	}

	public void setItem6(Character item6) {
		this.item6 = item6;
	}

	@Column(name = "ITEM7", length = 1)
	public Character getItem7() {
		return this.item7;
	}

	public void setItem7(Character item7) {
		this.item7 = item7;
	}

	@Column(name = "ITEM8", length = 1)
	public Character getItem8() {
		return this.item8;
	}

	public void setItem8(Character item8) {
		this.item8 = item8;
	}

	@Column(name = "ITEM9", length = 1)
	public Character getItem9() {
		return this.item9;
	}

	public void setItem9(Character item9) {
		this.item9 = item9;
	}

	@Column(name = "ITEM10", length = 1)
	public Character getItem10() {
		return this.item10;
	}

	public void setItem10(Character item10) {
		this.item10 = item10;
	}

	@Column(name = "ITEM11", length = 1)
	public Character getItem11() {
		return this.item11;
	}

	public void setItem11(Character item11) {
		this.item11 = item11;
	}

	@Column(name = "ITEM12", length = 1)
	public Character getItem12() {
		return this.item12;
	}

	public void setItem12(Character item12) {
		this.item12 = item12;
	}

	@Column(name = "ITEM13", length = 1)
	public Character getItem13() {
		return this.item13;
	}

	public void setItem13(Character item13) {
		this.item13 = item13;
	}

	@Column(name = "ITEM14", length = 1)
	public Character getItem14() {
		return this.item14;
	}

	public void setItem14(Character item14) {
		this.item14 = item14;
	}

	@Column(name = "ITEM15", length = 1)
	public Character getItem15() {
		return this.item15;
	}

	public void setItem15(Character item15) {
		this.item15 = item15;
	}

	@Column(name = "ITEM16", length = 1)
	public Character getItem16() {
		return this.item16;
	}

	public void setItem16(Character item16) {
		this.item16 = item16;
	}

	@Column(name = "ITEM17", length = 1)
	public Character getItem17() {
		return this.item17;
	}

	public void setItem17(Character item17) {
		this.item17 = item17;
	}

	@Column(name = "ITEM18", length = 1)
	public Character getItem18() {
		return this.item18;
	}

	public void setItem18(Character item18) {
		this.item18 = item18;
	}

	@Column(name = "ITEM19", length = 1)
	public Character getItem19() {
		return this.item19;
	}

	public void setItem19(Character item19) {
		this.item19 = item19;
	}

	@Column(name = "ITEM20", length = 1)
	public Character getItem20() {
		return this.item20;
	}

	public void setItem20(Character item20) {
		this.item20 = item20;
	}

	@Column(name = "ITEM21", length = 1)
	public Character getItem21() {
		return this.item21;
	}

	public void setItem21(Character item21) {
		this.item21 = item21;
	}

	@Column(name = "ITEM22", length = 1)
	public Character getItem22() {
		return this.item22;
	}

	public void setItem22(Character item22) {
		this.item22 = item22;
	}

	@Column(name = "ITEM23", length = 1)
	public Character getItem23() {
		return this.item23;
	}

	public void setItem23(Character item23) {
		this.item23 = item23;
	}

	@Column(name = "ITEM24", length = 1)
	public Character getItem24() {
		return this.item24;
	}

	public void setItem24(Character item24) {
		this.item24 = item24;
	}

	@Column(name = "ITEM25", length = 1)
	public Character getItem25() {
		return this.item25;
	}

	public void setItem25(Character item25) {
		this.item25 = item25;
	}

	@Column(name = "ITEM26", length = 1)
	public Character getItem26() {
		return this.item26;
	}

	public void setItem26(Character item26) {
		this.item26 = item26;
	}

	@Column(name = "ITEM27", length = 1)
	public Character getItem27() {
		return this.item27;
	}

	public void setItem27(Character item27) {
		this.item27 = item27;
	}

	@Column(name = "ITEM28", length = 1)
	public Character getItem28() {
		return this.item28;
	}

	public void setItem28(Character item28) {
		this.item28 = item28;
	}

	@Column(name = "ITEM29", length = 1)
	public Character getItem29() {
		return this.item29;
	}

	public void setItem29(Character item29) {
		this.item29 = item29;
	}

	@Column(name = "ITEM30", length = 1)
	public Character getItem30() {
		return this.item30;
	}

	public void setItem30(Character item30) {
		this.item30 = item30;
	}

	@Column(name = "ITEM31", length = 1)
	public Character getItem31() {
		return this.item31;
	}

	public void setItem31(Character item31) {
		this.item31 = item31;
	}

	@Column(name = "ITEM32", length = 1)
	public Character getItem32() {
		return this.item32;
	}

	public void setItem32(Character item32) {
		this.item32 = item32;
	}

	@Column(name = "ITEM33", length = 1)
	public Character getItem33() {
		return this.item33;
	}

	public void setItem33(Character item33) {
		this.item33 = item33;
	}

	@Column(name = "ITEM34", length = 1)
	public Character getItem34() {
		return this.item34;
	}

	public void setItem34(Character item34) {
		this.item34 = item34;
	}

	@Column(name = "ITEM35", length = 1)
	public Character getItem35() {
		return this.item35;
	}

	public void setItem35(Character item35) {
		this.item35 = item35;
	}

	@Column(name = "ITEM36", length = 1)
	public Character getItem36() {
		return this.item36;
	}

	public void setItem36(Character item36) {
		this.item36 = item36;
	}

	@Column(name = "ITEM37", length = 1)
	public Character getItem37() {
		return this.item37;
	}

	public void setItem37(Character item37) {
		this.item37 = item37;
	}

	@Column(name = "ITEM38", length = 1)
	public Character getItem38() {
		return this.item38;
	}

	public void setItem38(Character item38) {
		this.item38 = item38;
	}

	@Column(name = "ITEM39", length = 1)
	public Character getItem39() {
		return this.item39;
	}

	public void setItem39(Character item39) {
		this.item39 = item39;
	}

	@Column(name = "ITEM40", length = 1)
	public Character getItem40() {
		return this.item40;
	}

	public void setItem40(Character item40) {
		this.item40 = item40;
	}

	@Column(name = "ITEM41", length = 1)
	public Character getItem41() {
		return this.item41;
	}

	public void setItem41(Character item41) {
		this.item41 = item41;
	}

	@Column(name = "ITEM42", length = 1)
	public Character getItem42() {
		return this.item42;
	}

	public void setItem42(Character item42) {
		this.item42 = item42;
	}

	@Column(name = "ITEM43", length = 1)
	public Character getItem43() {
		return this.item43;
	}

	public void setItem43(Character item43) {
		this.item43 = item43;
	}

	@Column(name = "ITEM44", length = 1)
	public Character getItem44() {
		return this.item44;
	}

	public void setItem44(Character item44) {
		this.item44 = item44;
	}

	@Column(name = "ITEM45", length = 1)
	public Character getItem45() {
		return this.item45;
	}

	public void setItem45(Character item45) {
		this.item45 = item45;
	}

	@Column(name = "ITEM46", length = 1)
	public Character getItem46() {
		return this.item46;
	}

	public void setItem46(Character item46) {
		this.item46 = item46;
	}

	@Column(name = "ITEM47", length = 1)
	public Character getItem47() {
		return this.item47;
	}

	public void setItem47(Character item47) {
		this.item47 = item47;
	}

	@Column(name = "ITEM48", length = 1)
	public Character getItem48() {
		return this.item48;
	}

	public void setItem48(Character item48) {
		this.item48 = item48;
	}

	@Column(name = "ITEM49", length = 1)
	public Character getItem49() {
		return this.item49;
	}

	public void setItem49(Character item49) {
		this.item49 = item49;
	}

	@Column(name = "ITEM50", length = 1)
	public Character getItem50() {
		return this.item50;
	}

	public void setItem50(Character item50) {
		this.item50 = item50;
	}

	@Column(name = "ITEM51", length = 1)
	public Character getItem51() {
		return this.item51;
	}

	public void setItem51(Character item51) {
		this.item51 = item51;
	}

	@Column(name = "ITEM52", length = 1)
	public Character getItem52() {
		return this.item52;
	}

	public void setItem52(Character item52) {
		this.item52 = item52;
	}

	@Column(name = "ITEM53", length = 1)
	public Character getItem53() {
		return this.item53;
	}

	public void setItem53(Character item53) {
		this.item53 = item53;
	}

	@Column(name = "ITEM54", length = 1)
	public Character getItem54() {
		return this.item54;
	}

	public void setItem54(Character item54) {
		this.item54 = item54;
	}

	@Column(name = "ITEM55", length = 1)
	public Character getItem55() {
		return this.item55;
	}

	public void setItem55(Character item55) {
		this.item55 = item55;
	}

	@Column(name = "ITEM56", length = 1)
	public Character getItem56() {
		return this.item56;
	}

	public void setItem56(Character item56) {
		this.item56 = item56;
	}

	@Column(name = "ITEM57", length = 1)
	public Character getItem57() {
		return this.item57;
	}

	public void setItem57(Character item57) {
		this.item57 = item57;
	}

	@Column(name = "ITEM58", length = 1)
	public Character getItem58() {
		return this.item58;
	}

	public void setItem58(Character item58) {
		this.item58 = item58;
	}

	@Column(name = "ITEM59", length = 1)
	public Character getItem59() {
		return this.item59;
	}

	public void setItem59(Character item59) {
		this.item59 = item59;
	}

	@Column(name = "ITEM60", length = 1)
	public Character getItem60() {
		return this.item60;
	}

	public void setItem60(Character item60) {
		this.item60 = item60;
	}

	@Column(name = "ITEM61", length = 1)
	public Character getItem61() {
		return this.item61;
	}

	public void setItem61(Character item61) {
		this.item61 = item61;
	}

	@Column(name = "ITEM62", length = 1)
	public Character getItem62() {
		return this.item62;
	}

	public void setItem62(Character item62) {
		this.item62 = item62;
	}

	@Column(name = "ITEM63", length = 1)
	public Character getItem63() {
		return this.item63;
	}

	public void setItem63(Character item63) {
		this.item63 = item63;
	}

	@Column(name = "ITEM64", length = 1)
	public Character getItem64() {
		return this.item64;
	}

	public void setItem64(Character item64) {
		this.item64 = item64;
	}

	@Column(name = "ITEM65", length = 1)
	public Character getItem65() {
		return this.item65;
	}

	public void setItem65(Character item65) {
		this.item65 = item65;
	}

	@Column(name = "ITEM66", length = 1)
	public Character getItem66() {
		return this.item66;
	}

	public void setItem66(Character item66) {
		this.item66 = item66;
	}

	@Column(name = "ITEM67", length = 1)
	public Character getItem67() {
		return this.item67;
	}

	public void setItem67(Character item67) {
		this.item67 = item67;
	}

	@Column(name = "ITEM68", length = 1)
	public Character getItem68() {
		return this.item68;
	}

	public void setItem68(Character item68) {
		this.item68 = item68;
	}

	@Column(name = "ITEM69", length = 1)
	public Character getItem69() {
		return this.item69;
	}

	public void setItem69(Character item69) {
		this.item69 = item69;
	}

	@Column(name = "ITEM70", length = 1)
	public Character getItem70() {
		return this.item70;
	}

	public void setItem70(Character item70) {
		this.item70 = item70;
	}

	@Column(name = "ITEM71", length = 1)
	public Character getItem71() {
		return this.item71;
	}

	public void setItem71(Character item71) {
		this.item71 = item71;
	}

	@Column(name = "ITEM72", length = 1)
	public Character getItem72() {
		return this.item72;
	}

	public void setItem72(Character item72) {
		this.item72 = item72;
	}

	@Column(name = "ITEM73", length = 1)
	public Character getItem73() {
		return this.item73;
	}

	public void setItem73(Character item73) {
		this.item73 = item73;
	}

	@Column(name = "ITEM74", length = 1)
	public Character getItem74() {
		return this.item74;
	}

	public void setItem74(Character item74) {
		this.item74 = item74;
	}

	@Column(name = "ITEM75", length = 1)
	public Character getItem75() {
		return this.item75;
	}

	public void setItem75(Character item75) {
		this.item75 = item75;
	}

	@Column(name = "ITEM76", length = 1)
	public Character getItem76() {
		return this.item76;
	}

	public void setItem76(Character item76) {
		this.item76 = item76;
	}

	@Column(name = "ITEM77", length = 1)
	public Character getItem77() {
		return this.item77;
	}

	public void setItem77(Character item77) {
		this.item77 = item77;
	}

	@Column(name = "ITEM78", length = 1)
	public Character getItem78() {
		return this.item78;
	}

	public void setItem78(Character item78) {
		this.item78 = item78;
	}

	@Column(name = "ITEM79", length = 1)
	public Character getItem79() {
		return this.item79;
	}

	public void setItem79(Character item79) {
		this.item79 = item79;
	}

	@Column(name = "ITEM80", length = 1)
	public Character getItem80() {
		return this.item80;
	}

	public void setItem80(Character item80) {
		this.item80 = item80;
	}

	@Column(name = "ITEM81", length = 1)
	public Character getItem81() {
		return this.item81;
	}

	public void setItem81(Character item81) {
		this.item81 = item81;
	}

	@Column(name = "ITEM82", length = 1)
	public Character getItem82() {
		return this.item82;
	}

	public void setItem82(Character item82) {
		this.item82 = item82;
	}

	@Column(name = "ITEM83", length = 1)
	public Character getItem83() {
		return this.item83;
	}

	public void setItem83(Character item83) {
		this.item83 = item83;
	}

	@Column(name = "ITEM84", length = 1)
	public Character getItem84() {
		return this.item84;
	}

	public void setItem84(Character item84) {
		this.item84 = item84;
	}

	@Column(name = "ITEM85", length = 1)
	public Character getItem85() {
		return this.item85;
	}

	public void setItem85(Character item85) {
		this.item85 = item85;
	}

	@Column(name = "ITEM86", length = 1)
	public Character getItem86() {
		return this.item86;
	}

	public void setItem86(Character item86) {
		this.item86 = item86;
	}

	@Column(name = "ITEM87", length = 1)
	public Character getItem87() {
		return this.item87;
	}

	public void setItem87(Character item87) {
		this.item87 = item87;
	}

	@Column(name = "ITEM88", length = 1)
	public Character getItem88() {
		return this.item88;
	}

	public void setItem88(Character item88) {
		this.item88 = item88;
	}

	@Column(name = "ITEM89", length = 1)
	public Character getItem89() {
		return this.item89;
	}

	public void setItem89(Character item89) {
		this.item89 = item89;
	}

	@Column(name = "ITEM90", length = 1)
	public Character getItem90() {
		return this.item90;
	}

	public void setItem90(Character item90) {
		this.item90 = item90;
	}

	@Column(name = "ITEM91", length = 1)
	public Character getItem91() {
		return this.item91;
	}

	public void setItem91(Character item91) {
		this.item91 = item91;
	}

	@Column(name = "ITEM92", length = 1)
	public Character getItem92() {
		return this.item92;
	}

	public void setItem92(Character item92) {
		this.item92 = item92;
	}

	@Column(name = "ITEM93", length = 1)
	public Character getItem93() {
		return this.item93;
	}

	public void setItem93(Character item93) {
		this.item93 = item93;
	}

	@Column(name = "ITEM94", length = 1)
	public Character getItem94() {
		return this.item94;
	}

	public void setItem94(Character item94) {
		this.item94 = item94;
	}

	@Column(name = "ITEM95", length = 1)
	public Character getItem95() {
		return this.item95;
	}

	public void setItem95(Character item95) {
		this.item95 = item95;
	}

	@Column(name = "ITEM96", length = 1)
	public Character getItem96() {
		return this.item96;
	}

	public void setItem96(Character item96) {
		this.item96 = item96;
	}

	@Column(name = "ITEM97", length = 1)
	public Character getItem97() {
		return this.item97;
	}

	public void setItem97(Character item97) {
		this.item97 = item97;
	}

	@Column(name = "ITEM98", length = 1)
	public Character getItem98() {
		return this.item98;
	}

	public void setItem98(Character item98) {
		this.item98 = item98;
	}

	@Column(name = "ITEM99", length = 1)
	public Character getItem99() {
		return this.item99;
	}

	public void setItem99(Character item99) {
		this.item99 = item99;
	}

	@Column(name = "ITEM100", length = 1)
	public Character getItem100() {
		return this.item100;
	}

	public void setItem100(Character item100) {
		this.item100 = item100;
	}

	@Column(name = "ITEM101", length = 1)
	public Character getItem101() {
		return this.item101;
	}

	public void setItem101(Character item101) {
		this.item101 = item101;
	}

	@Column(name = "ITEM102", length = 1)
	public Character getItem102() {
		return this.item102;
	}

	public void setItem102(Character item102) {
		this.item102 = item102;
	}

	@Column(name = "ITEM103", length = 1)
	public Character getItem103() {
		return this.item103;
	}

	public void setItem103(Character item103) {
		this.item103 = item103;
	}

	@Column(name = "ITEM104", length = 1)
	public Character getItem104() {
		return this.item104;
	}

	public void setItem104(Character item104) {
		this.item104 = item104;
	}

	@Column(name = "ITEM105", length = 1)
	public Character getItem105() {
		return this.item105;
	}

	public void setItem105(Character item105) {
		this.item105 = item105;
	}

	@Column(name = "ITEM106", length = 1)
	public Character getItem106() {
		return this.item106;
	}

	public void setItem106(Character item106) {
		this.item106 = item106;
	}

	@Column(name = "ITEM107", length = 1)
	public Character getItem107() {
		return this.item107;
	}

	public void setItem107(Character item107) {
		this.item107 = item107;
	}

	@Column(name = "ITEM108", length = 1)
	public Character getItem108() {
		return this.item108;
	}

	public void setItem108(Character item108) {
		this.item108 = item108;
	}

	@Column(name = "ITEM109", length = 1)
	public Character getItem109() {
		return this.item109;
	}

	public void setItem109(Character item109) {
		this.item109 = item109;
	}

	@Column(name = "ITEM110", length = 1)
	public Character getItem110() {
		return this.item110;
	}

	public void setItem110(Character item110) {
		this.item110 = item110;
	}

	@Column(name = "ITEM111", length = 1)
	public Character getItem111() {
		return this.item111;
	}

	public void setItem111(Character item111) {
		this.item111 = item111;
	}

	@Column(name = "ITEM112", length = 1)
	public Character getItem112() {
		return this.item112;
	}

	public void setItem112(Character item112) {
		this.item112 = item112;
	}

	@Column(name = "ITEM113", length = 1)
	public Character getItem113() {
		return this.item113;
	}

	public void setItem113(Character item113) {
		this.item113 = item113;
	}

	@Column(name = "ITEM114", length = 1)
	public Character getItem114() {
		return this.item114;
	}

	public void setItem114(Character item114) {
		this.item114 = item114;
	}

	@Column(name = "ITEM115", length = 1)
	public Character getItem115() {
		return this.item115;
	}

	public void setItem115(Character item115) {
		this.item115 = item115;
	}

	@Column(name = "ITEM116", length = 1)
	public Character getItem116() {
		return this.item116;
	}

	public void setItem116(Character item116) {
		this.item116 = item116;
	}

	@Column(name = "ITEM117", length = 1)
	public Character getItem117() {
		return this.item117;
	}

	public void setItem117(Character item117) {
		this.item117 = item117;
	}

	@Column(name = "ITEM118", length = 1)
	public Character getItem118() {
		return this.item118;
	}

	public void setItem118(Character item118) {
		this.item118 = item118;
	}

	@Column(name = "ITEM119", length = 1)
	public Character getItem119() {
		return this.item119;
	}

	public void setItem119(Character item119) {
		this.item119 = item119;
	}

	@Column(name = "ITEM120", length = 1)
	public Character getItem120() {
		return this.item120;
	}

	public void setItem120(Character item120) {
		this.item120 = item120;
	}

	@Column(name = "ITEM121", length = 1)
	public Character getItem121() {
		return this.item121;
	}

	public void setItem121(Character item121) {
		this.item121 = item121;
	}

	@Column(name = "ITEM122", length = 1)
	public Character getItem122() {
		return this.item122;
	}

	public void setItem122(Character item122) {
		this.item122 = item122;
	}

	@Column(name = "ITEM123", length = 1)
	public Character getItem123() {
		return this.item123;
	}

	public void setItem123(Character item123) {
		this.item123 = item123;
	}

	@Column(name = "ITEM124", length = 1)
	public Character getItem124() {
		return this.item124;
	}

	public void setItem124(Character item124) {
		this.item124 = item124;
	}

	@Column(name = "ITEM125", length = 1)
	public Character getItem125() {
		return this.item125;
	}

	public void setItem125(Character item125) {
		this.item125 = item125;
	}

	@Column(name = "ITEM126", length = 1)
	public Character getItem126() {
		return this.item126;
	}

	public void setItem126(Character item126) {
		this.item126 = item126;
	}

	@Column(name = "ITEM127", length = 1)
	public Character getItem127() {
		return this.item127;
	}

	public void setItem127(Character item127) {
		this.item127 = item127;
	}

	@Column(name = "ITEM128", length = 1)
	public Character getItem128() {
		return this.item128;
	}

	public void setItem128(Character item128) {
		this.item128 = item128;
	}

	@Column(name = "ITEM129", length = 1)
	public Character getItem129() {
		return this.item129;
	}

	public void setItem129(Character item129) {
		this.item129 = item129;
	}

	@Column(name = "ITEM130", length = 1)
	public Character getItem130() {
		return this.item130;
	}

	public void setItem130(Character item130) {
		this.item130 = item130;
	}

	@Column(name = "ITEM131", length = 1)
	public Character getItem131() {
		return this.item131;
	}

	public void setItem131(Character item131) {
		this.item131 = item131;
	}

	@Column(name = "ITEM132", length = 1)
	public Character getItem132() {
		return this.item132;
	}

	public void setItem132(Character item132) {
		this.item132 = item132;
	}

	@Column(name = "ITEM133", length = 1)
	public Character getItem133() {
		return this.item133;
	}

	public void setItem133(Character item133) {
		this.item133 = item133;
	}

	@Column(name = "ITEM134", length = 1)
	public Character getItem134() {
		return this.item134;
	}

	public void setItem134(Character item134) {
		this.item134 = item134;
	}

	@Column(name = "ITEM135", length = 1)
	public Character getItem135() {
		return this.item135;
	}

	public void setItem135(Character item135) {
		this.item135 = item135;
	}

	@Column(name = "ITEM136", length = 1)
	public Character getItem136() {
		return this.item136;
	}

	public void setItem136(Character item136) {
		this.item136 = item136;
	}

	@Column(name = "ITEM137", length = 1)
	public Character getItem137() {
		return this.item137;
	}

	public void setItem137(Character item137) {
		this.item137 = item137;
	}

	@Column(name = "ITEM138", length = 1)
	public Character getItem138() {
		return this.item138;
	}

	public void setItem138(Character item138) {
		this.item138 = item138;
	}

	@Column(name = "ITEM139", length = 1)
	public Character getItem139() {
		return this.item139;
	}

	public void setItem139(Character item139) {
		this.item139 = item139;
	}

	@Column(name = "ITEM140", length = 1)
	public Character getItem140() {
		return this.item140;
	}

	public void setItem140(Character item140) {
		this.item140 = item140;
	}

	@Column(name = "ITEM141", length = 1)
	public Character getItem141() {
		return this.item141;
	}

	public void setItem141(Character item141) {
		this.item141 = item141;
	}

	@Column(name = "ITEM142", length = 1)
	public Character getItem142() {
		return this.item142;
	}

	public void setItem142(Character item142) {
		this.item142 = item142;
	}

	@Column(name = "ITEM143", length = 1)
	public Character getItem143() {
		return this.item143;
	}

	public void setItem143(Character item143) {
		this.item143 = item143;
	}

	@Column(name = "ITEM144", length = 1)
	public Character getItem144() {
		return this.item144;
	}

	public void setItem144(Character item144) {
		this.item144 = item144;
	}

	@Column(name = "ITEM145", length = 1)
	public Character getItem145() {
		return this.item145;
	}

	public void setItem145(Character item145) {
		this.item145 = item145;
	}

	@Column(name = "ITEM146", length = 1)
	public Character getItem146() {
		return this.item146;
	}

	public void setItem146(Character item146) {
		this.item146 = item146;
	}

	@Column(name = "ITEM147", length = 1)
	public Character getItem147() {
		return this.item147;
	}

	public void setItem147(Character item147) {
		this.item147 = item147;
	}

	@Column(name = "ITEM148", length = 1)
	public Character getItem148() {
		return this.item148;
	}

	public void setItem148(Character item148) {
		this.item148 = item148;
	}

	@Column(name = "ITEM149", length = 1)
	public Character getItem149() {
		return this.item149;
	}

	public void setItem149(Character item149) {
		this.item149 = item149;
	}

	@Column(name = "ITEM150", length = 1)
	public Character getItem150() {
		return this.item150;
	}

	public void setItem150(Character item150) {
		this.item150 = item150;
	}

	@Column(name = "ITEM151", length = 1)
	public Character getItem151() {
		return this.item151;
	}

	public void setItem151(Character item151) {
		this.item151 = item151;
	}

	@Column(name = "ITEM152", length = 1)
	public Character getItem152() {
		return this.item152;
	}

	public void setItem152(Character item152) {
		this.item152 = item152;
	}

	@Column(name = "ITEM153", length = 1)
	public Character getItem153() {
		return this.item153;
	}

	public void setItem153(Character item153) {
		this.item153 = item153;
	}

	@Column(name = "ITEM154", length = 1)
	public Character getItem154() {
		return this.item154;
	}

	public void setItem154(Character item154) {
		this.item154 = item154;
	}

	@Column(name = "ITEM155", length = 1)
	public Character getItem155() {
		return this.item155;
	}

	public void setItem155(Character item155) {
		this.item155 = item155;
	}

	@Column(name = "ITEM156", length = 1)
	public Character getItem156() {
		return this.item156;
	}

	public void setItem156(Character item156) {
		this.item156 = item156;
	}

	@Column(name = "ITEM157", length = 1)
	public Character getItem157() {
		return this.item157;
	}

	public void setItem157(Character item157) {
		this.item157 = item157;
	}

	@Column(name = "ITEM158", length = 1)
	public Character getItem158() {
		return this.item158;
	}

	public void setItem158(Character item158) {
		this.item158 = item158;
	}

	@Column(name = "ITEM159", length = 1)
	public Character getItem159() {
		return this.item159;
	}

	public void setItem159(Character item159) {
		this.item159 = item159;
	}

	@Column(name = "ITEM160", length = 1)
	public Character getItem160() {
		return this.item160;
	}

	public void setItem160(Character item160) {
		this.item160 = item160;
	}

	@Column(name = "ITEM161", length = 1)
	public Character getItem161() {
		return this.item161;
	}

	public void setItem161(Character item161) {
		this.item161 = item161;
	}

	@Column(name = "ITEM162", length = 1)
	public Character getItem162() {
		return this.item162;
	}

	public void setItem162(Character item162) {
		this.item162 = item162;
	}

	@Column(name = "ITEM163", length = 1)
	public Character getItem163() {
		return this.item163;
	}

	public void setItem163(Character item163) {
		this.item163 = item163;
	}

	@Column(name = "ITEM164", length = 1)
	public Character getItem164() {
		return this.item164;
	}

	public void setItem164(Character item164) {
		this.item164 = item164;
	}

	@Column(name = "ITEM165", length = 1)
	public Character getItem165() {
		return this.item165;
	}

	public void setItem165(Character item165) {
		this.item165 = item165;
	}

	@Column(name = "ITEM166", length = 1)
	public Character getItem166() {
		return this.item166;
	}

	public void setItem166(Character item166) {
		this.item166 = item166;
	}

	@Column(name = "ITEM167", length = 1)
	public Character getItem167() {
		return this.item167;
	}

	public void setItem167(Character item167) {
		this.item167 = item167;
	}

	@Column(name = "ITEM168", length = 1)
	public Character getItem168() {
		return this.item168;
	}

	public void setItem168(Character item168) {
		this.item168 = item168;
	}

	@Column(name = "ITEM169", length = 1)
	public Character getItem169() {
		return this.item169;
	}

	public void setItem169(Character item169) {
		this.item169 = item169;
	}

	@Column(name = "ITEM170", length = 1)
	public Character getItem170() {
		return this.item170;
	}

	public void setItem170(Character item170) {
		this.item170 = item170;
	}

	@Column(name = "ITEM171", length = 1)
	public Character getItem171() {
		return this.item171;
	}

	public void setItem171(Character item171) {
		this.item171 = item171;
	}

	@Column(name = "ITEM172", length = 1)
	public Character getItem172() {
		return this.item172;
	}

	public void setItem172(Character item172) {
		this.item172 = item172;
	}

	@Column(name = "ITEM173", length = 1)
	public Character getItem173() {
		return this.item173;
	}

	public void setItem173(Character item173) {
		this.item173 = item173;
	}

	@Column(name = "ITEM174", length = 1)
	public Character getItem174() {
		return this.item174;
	}

	public void setItem174(Character item174) {
		this.item174 = item174;
	}

	@Column(name = "ITEM175", length = 1)
	public Character getItem175() {
		return this.item175;
	}

	public void setItem175(Character item175) {
		this.item175 = item175;
	}

	@Column(name = "ITEM176", length = 1)
	public Character getItem176() {
		return this.item176;
	}

	public void setItem176(Character item176) {
		this.item176 = item176;
	}

	@Column(name = "ITEM177", length = 1)
	public Character getItem177() {
		return this.item177;
	}

	public void setItem177(Character item177) {
		this.item177 = item177;
	}

	@Column(name = "ITEM178", length = 1)
	public Character getItem178() {
		return this.item178;
	}

	public void setItem178(Character item178) {
		this.item178 = item178;
	}

	@Column(name = "ITEM179", length = 1)
	public Character getItem179() {
		return this.item179;
	}

	public void setItem179(Character item179) {
		this.item179 = item179;
	}

	@Column(name = "ITEM180", length = 1)
	public Character getItem180() {
		return this.item180;
	}

	public void setItem180(Character item180) {
		this.item180 = item180;
	}

	@Column(name = "ITEM181", length = 1)
	public Character getItem181() {
		return this.item181;
	}

	public void setItem181(Character item181) {
		this.item181 = item181;
	}

	@Column(name = "ITEM182", length = 1)
	public Character getItem182() {
		return this.item182;
	}

	public void setItem182(Character item182) {
		this.item182 = item182;
	}

	@Column(name = "ITEM183", length = 1)
	public Character getItem183() {
		return this.item183;
	}

	public void setItem183(Character item183) {
		this.item183 = item183;
	}

	@Column(name = "ITEM184", length = 1)
	public Character getItem184() {
		return this.item184;
	}

	public void setItem184(Character item184) {
		this.item184 = item184;
	}

	@Column(name = "ITEM185", length = 1)
	public Character getItem185() {
		return this.item185;
	}

	public void setItem185(Character item185) {
		this.item185 = item185;
	}

	@Column(name = "ITEM186", length = 1)
	public Character getItem186() {
		return this.item186;
	}

	public void setItem186(Character item186) {
		this.item186 = item186;
	}

	@Column(name = "ITEM187", length = 1)
	public Character getItem187() {
		return this.item187;
	}

	public void setItem187(Character item187) {
		this.item187 = item187;
	}

	@Column(name = "ITEM188", length = 1)
	public Character getItem188() {
		return this.item188;
	}

	public void setItem188(Character item188) {
		this.item188 = item188;
	}

	@Column(name = "ITEM189", length = 1)
	public Character getItem189() {
		return this.item189;
	}

	public void setItem189(Character item189) {
		this.item189 = item189;
	}

	@Column(name = "ITEM190", length = 1)
	public Character getItem190() {
		return this.item190;
	}

	public void setItem190(Character item190) {
		this.item190 = item190;
	}

	@Column(name = "ITEM191", length = 1)
	public Character getItem191() {
		return this.item191;
	}

	public void setItem191(Character item191) {
		this.item191 = item191;
	}

	@Column(name = "ITEM192", length = 1)
	public Character getItem192() {
		return this.item192;
	}

	public void setItem192(Character item192) {
		this.item192 = item192;
	}

	@Column(name = "ITEM193", length = 1)
	public Character getItem193() {
		return this.item193;
	}

	public void setItem193(Character item193) {
		this.item193 = item193;
	}

	@Column(name = "ITEM194", length = 1)
	public Character getItem194() {
		return this.item194;
	}

	public void setItem194(Character item194) {
		this.item194 = item194;
	}

	@Column(name = "ITEM195", length = 1)
	public Character getItem195() {
		return this.item195;
	}

	public void setItem195(Character item195) {
		this.item195 = item195;
	}

	@Column(name = "ITEM196", length = 1)
	public Character getItem196() {
		return this.item196;
	}

	public void setItem196(Character item196) {
		this.item196 = item196;
	}

	@Column(name = "ITEM197", length = 1)
	public Character getItem197() {
		return this.item197;
	}

	public void setItem197(Character item197) {
		this.item197 = item197;
	}

	@Column(name = "ITEM198", length = 1)
	public Character getItem198() {
		return this.item198;
	}

	public void setItem198(Character item198) {
		this.item198 = item198;
	}

	@Column(name = "ITEM199", length = 1)
	public Character getItem199() {
		return this.item199;
	}

	public void setItem199(Character item199) {
		this.item199 = item199;
	}

	@Column(name = "ITEM200", length = 1)
	public Character getItem200() {
		return this.item200;
	}

	public void setItem200(Character item200) {
		this.item200 = item200;
	}

}
