package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FLogin generated by hbm2java
 */
@Entity
@Table(name = "F_LOGIN", schema = "DB2ADMIN")
public class FLogin implements java.io.Serializable {

	private String pcid;
	private String userid;
	private String pwd;
	private Integer loginDate;
	private Integer loginTime;
	private Integer loginlDate;
	private Integer loginlTime;

	public FLogin() {
	}

	public FLogin(String pcid) {
		this.pcid = pcid;
	}

	public FLogin(String pcid, String userid, String pwd, Integer loginDate,
			Integer loginTime, Integer loginlDate, Integer loginlTime) {
		this.pcid = pcid;
		this.userid = userid;
		this.pwd = pwd;
		this.loginDate = loginDate;
		this.loginTime = loginTime;
		this.loginlDate = loginlDate;
		this.loginlTime = loginlTime;
	}

	@Id
	@Column(name = "PCID", unique = true, nullable = false, length = 20)
	public String getPcid() {
		return this.pcid;
	}

	public void setPcid(String pcid) {
		this.pcid = pcid;
	}

	@Column(name = "USERID", length = 10)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "PWD", length = 16)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "LOGIN_DATE", precision = 8, scale = 0)
	public Integer getLoginDate() {
		return this.loginDate;
	}

	public void setLoginDate(Integer loginDate) {
		this.loginDate = loginDate;
	}

	@Column(name = "LOGIN_TIME", precision = 6, scale = 0)
	public Integer getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Integer loginTime) {
		this.loginTime = loginTime;
	}

	@Column(name = "LOGINL_DATE", precision = 8, scale = 0)
	public Integer getLoginlDate() {
		return this.loginlDate;
	}

	public void setLoginlDate(Integer loginlDate) {
		this.loginlDate = loginlDate;
	}

	@Column(name = "LOGINL_TIME", precision = 6, scale = 0)
	public Integer getLoginlTime() {
		return this.loginlTime;
	}

	public void setLoginlTime(Integer loginlTime) {
		this.loginlTime = loginlTime;
	}

}
