package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FLog generated by hbm2java
 */
@Entity
@Table(name = "F_LOG", schema = "DB2ADMIN")
public class FLog implements java.io.Serializable {

	private FLogId id;
	private String pcid;

	public FLog() {
	}

	public FLog(FLogId id) {
		this.id = id;
	}

	public FLog(FLogId id, String pcid) {
		this.id = id;
		this.pcid = pcid;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userUser", column = @Column(name = "USER_USER", nullable = false, length = 10)),
			@AttributeOverride(name = "actDate", column = @Column(name = "ACT_DATE", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "actTime", column = @Column(name = "ACT_TIME", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "menugrpCode", column = @Column(name = "MENUGRP_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "menuexeCode", column = @Column(name = "MENUEXE_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "actionType", column = @Column(name = "ACTION_TYPE", nullable = false, length = 2)),
			@AttributeOverride(name = "text", column = @Column(name = "TEXT", nullable = false, length = 100)) })
	public FLogId getId() {
		return this.id;
	}

	public void setId(FLogId id) {
		this.id = id;
	}

	@Column(name = "PCID", length = 20)
	public String getPcid() {
		return this.pcid;
	}

	public void setPcid(String pcid) {
		this.pcid = pcid;
	}

}
