package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FSlp generated by hbm2java
 */
@Entity
@Table(name = "F_SLP", schema = "DB2ADMIN")
public class FSlp implements java.io.Serializable {

	private FSlpId id;
	private String slpName;
	private Integer slpnew;
	private Integer slpmin;
	private Integer slpmax;
	private String addUser;
	private String addPc;
	private Integer addDate;
	private Integer addTime;
	private String lastupUser;
	private String lastupPc;
	private Integer lastupDate;
	private Integer lastupTime;

	public FSlp() {
	}

	public FSlp(FSlpId id) {
		this.id = id;
	}

	public FSlp(FSlpId id, String slpName, Integer slpnew, Integer slpmin,
			Integer slpmax, String addUser, String addPc, Integer addDate,
			Integer addTime, String lastupUser, String lastupPc,
			Integer lastupDate, Integer lastupTime) {
		this.id = id;
		this.slpName = slpName;
		this.slpnew = slpnew;
		this.slpmin = slpmin;
		this.slpmax = slpmax;
		this.addUser = addUser;
		this.addPc = addPc;
		this.addDate = addDate;
		this.addTime = addTime;
		this.lastupUser = lastupUser;
		this.lastupPc = lastupPc;
		this.lastupDate = lastupDate;
		this.lastupTime = lastupTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "slpType", column = @Column(name = "SLP_TYPE", nullable = false, length = 3)),
			@AttributeOverride(name = "slpdate", column = @Column(name = "SLPDATE", nullable = false, length = 4)) })
	public FSlpId getId() {
		return this.id;
	}

	public void setId(FSlpId id) {
		this.id = id;
	}

	@Column(name = "SLP_NAME", length = 30)
	public String getSlpName() {
		return this.slpName;
	}

	public void setSlpName(String slpName) {
		this.slpName = slpName;
	}

	@Column(name = "SLPNEW", precision = 6, scale = 0)
	public Integer getSlpnew() {
		return this.slpnew;
	}

	public void setSlpnew(Integer slpnew) {
		this.slpnew = slpnew;
	}

	@Column(name = "SLPMIN", precision = 6, scale = 0)
	public Integer getSlpmin() {
		return this.slpmin;
	}

	public void setSlpmin(Integer slpmin) {
		this.slpmin = slpmin;
	}

	@Column(name = "SLPMAX", precision = 6, scale = 0)
	public Integer getSlpmax() {
		return this.slpmax;
	}

	public void setSlpmax(Integer slpmax) {
		this.slpmax = slpmax;
	}

	@Column(name = "ADD_USER", length = 10)
	public String getAddUser() {
		return this.addUser;
	}

	public void setAddUser(String addUser) {
		this.addUser = addUser;
	}

	@Column(name = "ADD_PC", length = 30)
	public String getAddPc() {
		return this.addPc;
	}

	public void setAddPc(String addPc) {
		this.addPc = addPc;
	}

	@Column(name = "ADD_DATE", precision = 8, scale = 0)
	public Integer getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Integer addDate) {
		this.addDate = addDate;
	}

	@Column(name = "ADD_TIME", precision = 6, scale = 0)
	public Integer getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Integer addTime) {
		this.addTime = addTime;
	}

	@Column(name = "LASTUP_USER", length = 10)
	public String getLastupUser() {
		return this.lastupUser;
	}

	public void setLastupUser(String lastupUser) {
		this.lastupUser = lastupUser;
	}

	@Column(name = "LASTUP_PC", length = 30)
	public String getLastupPc() {
		return this.lastupPc;
	}

	public void setLastupPc(String lastupPc) {
		this.lastupPc = lastupPc;
	}

	@Column(name = "LASTUP_DATE", precision = 8, scale = 0)
	public Integer getLastupDate() {
		return this.lastupDate;
	}

	public void setLastupDate(Integer lastupDate) {
		this.lastupDate = lastupDate;
	}

	@Column(name = "LASTUP_TIME", precision = 6, scale = 0)
	public Integer getLastupTime() {
		return this.lastupTime;
	}

	public void setLastupTime(Integer lastupTime) {
		this.lastupTime = lastupTime;
	}

}
