package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FSlpId generated by hbm2java
 */
@Embeddable
public class FSlpId implements java.io.Serializable {

	private String slpType;
	private String slpdate;

	public FSlpId() {
	}

	public FSlpId(String slpType, String slpdate) {
		this.slpType = slpType;
		this.slpdate = slpdate;
	}

	@Column(name = "SLP_TYPE", nullable = false, length = 3)
	public String getSlpType() {
		return this.slpType;
	}

	public void setSlpType(String slpType) {
		this.slpType = slpType;
	}

	@Column(name = "SLPDATE", nullable = false, length = 4)
	public String getSlpdate() {
		return this.slpdate;
	}

	public void setSlpdate(String slpdate) {
		this.slpdate = slpdate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FSlpId))
			return false;
		FSlpId castOther = (FSlpId) other;

		return ((this.getSlpType() == castOther.getSlpType()) || (this
				.getSlpType() != null && castOther.getSlpType() != null && this
				.getSlpType().equals(castOther.getSlpType())))
				&& ((this.getSlpdate() == castOther.getSlpdate()) || (this
						.getSlpdate() != null && castOther.getSlpdate() != null && this
						.getSlpdate().equals(castOther.getSlpdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSlpType() == null ? 0 : this.getSlpType().hashCode());
		result = 37 * result
				+ (getSlpdate() == null ? 0 : this.getSlpdate().hashCode());
		return result;
	}

}
