package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MCalendar generated by hbm2java
 */
@Entity
@Table(name = "M_CALENDAR", schema = "DB2ADMIN")
public class MCalendar implements java.io.Serializable {

	private int chst8Date;
	private Integer chst6Date;
	private String eraType;
	private Integer harm6Date;
	private Short oldcDate;
	private String weekType;
	private String gotwType;
	private String holdType;
	private String holdName;
	private String other1Name;
	private String other2Name;
	private String other3Name;
	private String other4Name;
	private String other5Name;
	private String memorandum1;
	private String memorandum2;

	public MCalendar() {
	}

	public MCalendar(int chst8Date) {
		this.chst8Date = chst8Date;
	}

	public MCalendar(int chst8Date, Integer chst6Date, String eraType,
			Integer harm6Date, Short oldcDate, String weekType,
			String gotwType, String holdType, String holdName,
			String other1Name, String other2Name, String other3Name,
			String other4Name, String other5Name, String memorandum1,
			String memorandum2) {
		this.chst8Date = chst8Date;
		this.chst6Date = chst6Date;
		this.eraType = eraType;
		this.harm6Date = harm6Date;
		this.oldcDate = oldcDate;
		this.weekType = weekType;
		this.gotwType = gotwType;
		this.holdType = holdType;
		this.holdName = holdName;
		this.other1Name = other1Name;
		this.other2Name = other2Name;
		this.other3Name = other3Name;
		this.other4Name = other4Name;
		this.other5Name = other5Name;
		this.memorandum1 = memorandum1;
		this.memorandum2 = memorandum2;
	}

	@Id
	@Column(name = "CHST8_DATE", unique = true, nullable = false, precision = 8, scale = 0)
	public int getChst8Date() {
		return this.chst8Date;
	}

	public void setChst8Date(int chst8Date) {
		this.chst8Date = chst8Date;
	}

	@Column(name = "CHST6_DATE", precision = 6, scale = 0)
	public Integer getChst6Date() {
		return this.chst6Date;
	}

	public void setChst6Date(Integer chst6Date) {
		this.chst6Date = chst6Date;
	}

	@Column(name = "ERA_TYPE", length = 2)
	public String getEraType() {
		return this.eraType;
	}

	public void setEraType(String eraType) {
		this.eraType = eraType;
	}

	@Column(name = "HARM6_DATE", precision = 6, scale = 0)
	public Integer getHarm6Date() {
		return this.harm6Date;
	}

	public void setHarm6Date(Integer harm6Date) {
		this.harm6Date = harm6Date;
	}

	@Column(name = "OLDC_DATE", precision = 4, scale = 0)
	public Short getOldcDate() {
		return this.oldcDate;
	}

	public void setOldcDate(Short oldcDate) {
		this.oldcDate = oldcDate;
	}

	@Column(name = "WEEK_TYPE", length = 2)
	public String getWeekType() {
		return this.weekType;
	}

	public void setWeekType(String weekType) {
		this.weekType = weekType;
	}

	@Column(name = "GOTW_TYPE", length = 2)
	public String getGotwType() {
		return this.gotwType;
	}

	public void setGotwType(String gotwType) {
		this.gotwType = gotwType;
	}

	@Column(name = "HOLD_TYPE", length = 2)
	public String getHoldType() {
		return this.holdType;
	}

	public void setHoldType(String holdType) {
		this.holdType = holdType;
	}

	@Column(name = "HOLD_NAME", length = 42)
	public String getHoldName() {
		return this.holdName;
	}

	public void setHoldName(String holdName) {
		this.holdName = holdName;
	}

	@Column(name = "OTHER1_NAME", length = 42)
	public String getOther1Name() {
		return this.other1Name;
	}

	public void setOther1Name(String other1Name) {
		this.other1Name = other1Name;
	}

	@Column(name = "OTHER2_NAME", length = 42)
	public String getOther2Name() {
		return this.other2Name;
	}

	public void setOther2Name(String other2Name) {
		this.other2Name = other2Name;
	}

	@Column(name = "OTHER3_NAME", length = 42)
	public String getOther3Name() {
		return this.other3Name;
	}

	public void setOther3Name(String other3Name) {
		this.other3Name = other3Name;
	}

	@Column(name = "OTHER4_NAME", length = 42)
	public String getOther4Name() {
		return this.other4Name;
	}

	public void setOther4Name(String other4Name) {
		this.other4Name = other4Name;
	}

	@Column(name = "OTHER5_NAME", length = 42)
	public String getOther5Name() {
		return this.other5Name;
	}

	public void setOther5Name(String other5Name) {
		this.other5Name = other5Name;
	}

	@Column(name = "MEMORANDUM1", length = 100)
	public String getMemorandum1() {
		return this.memorandum1;
	}

	public void setMemorandum1(String memorandum1) {
		this.memorandum1 = memorandum1;
	}

	@Column(name = "MEMORANDUM2", length = 100)
	public String getMemorandum2() {
		return this.memorandum2;
	}

	public void setMemorandum2(String memorandum2) {
		this.memorandum2 = memorandum2;
	}

}
