package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MClrctlId generated by hbm2java
 */
@Embeddable
public class MClrctlId implements java.io.Serializable {

	private String clrKey;
	private String userid;

	public MClrctlId() {
	}

	public MClrctlId(String clrKey, String userid) {
		this.clrKey = clrKey;
		this.userid = userid;
	}

	@Column(name = "CLR_KEY", nullable = false, length = 10)
	public String getClrKey() {
		return this.clrKey;
	}

	public void setClrKey(String clrKey) {
		this.clrKey = clrKey;
	}

	@Column(name = "USERID", nullable = false, length = 10)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MClrctlId))
			return false;
		MClrctlId castOther = (MClrctlId) other;

		return ((this.getClrKey() == castOther.getClrKey()) || (this
				.getClrKey() != null && castOther.getClrKey() != null && this
				.getClrKey().equals(castOther.getClrKey())))
				&& ((this.getUserid() == castOther.getUserid()) || (this
						.getUserid() != null && castOther.getUserid() != null && this
						.getUserid().equals(castOther.getUserid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getClrKey() == null ? 0 : this.getClrKey().hashCode());
		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		return result;
	}

}
