package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MColor generated by hbm2java
 */
@Entity
@Table(name = "M_COLOR", schema = "DB2ADMIN")
public class MColor implements java.io.Serializable {

	private MColorId id;
	private String colorName;
	private String colorRname;
	private Character defaultType;
	private Character dspFlg;
	private Short dsporderNo;
	private Character colortype;
	private Short bclrRed;
	private Short bclrGreen;
	private Short bclrBlue;
	private Short fclrRed;
	private Short fclrGreen;
	private Short fclrBlue;
	private String addUser;
	private String addPc;
	private Integer addDate;
	private Integer addTime;
	private String lastupUser;
	private String lastupPc;
	private Integer lastupDate;
	private Integer lastupTime;

	public MColor() {
	}

	public MColor(MColorId id) {
		this.id = id;
	}

	public MColor(MColorId id, String colorName, String colorRname,
			Character defaultType, Character dspFlg, Short dsporderNo,
			Character colortype, Short bclrRed, Short bclrGreen,
			Short bclrBlue, Short fclrRed, Short fclrGreen, Short fclrBlue,
			String addUser, String addPc, Integer addDate, Integer addTime,
			String lastupUser, String lastupPc, Integer lastupDate,
			Integer lastupTime) {
		this.id = id;
		this.colorName = colorName;
		this.colorRname = colorRname;
		this.defaultType = defaultType;
		this.dspFlg = dspFlg;
		this.dsporderNo = dsporderNo;
		this.colortype = colortype;
		this.bclrRed = bclrRed;
		this.bclrGreen = bclrGreen;
		this.bclrBlue = bclrBlue;
		this.fclrRed = fclrRed;
		this.fclrGreen = fclrGreen;
		this.fclrBlue = fclrBlue;
		this.addUser = addUser;
		this.addPc = addPc;
		this.addDate = addDate;
		this.addTime = addTime;
		this.lastupUser = lastupUser;
		this.lastupPc = lastupPc;
		this.lastupDate = lastupDate;
		this.lastupTime = lastupTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "colorclsCode", column = @Column(name = "COLORCLS_CODE", nullable = false, length = 8)),
			@AttributeOverride(name = "colorCode", column = @Column(name = "COLOR_CODE", nullable = false, length = 2)) })
	public MColorId getId() {
		return this.id;
	}

	public void setId(MColorId id) {
		this.id = id;
	}

	@Column(name = "COLOR_NAME", length = 40)
	public String getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	@Column(name = "COLOR_RNAME", length = 6)
	public String getColorRname() {
		return this.colorRname;
	}

	public void setColorRname(String colorRname) {
		this.colorRname = colorRname;
	}

	@Column(name = "DEFAULT_TYPE", length = 1)
	public Character getDefaultType() {
		return this.defaultType;
	}

	public void setDefaultType(Character defaultType) {
		this.defaultType = defaultType;
	}

	@Column(name = "DSP_FLG", length = 1)
	public Character getDspFlg() {
		return this.dspFlg;
	}

	public void setDspFlg(Character dspFlg) {
		this.dspFlg = dspFlg;
	}

	@Column(name = "DSPORDER_NO", precision = 3, scale = 0)
	public Short getDsporderNo() {
		return this.dsporderNo;
	}

	public void setDsporderNo(Short dsporderNo) {
		this.dsporderNo = dsporderNo;
	}

	@Column(name = "COLORTYPE", length = 1)
	public Character getColortype() {
		return this.colortype;
	}

	public void setColortype(Character colortype) {
		this.colortype = colortype;
	}

	@Column(name = "BCLR_RED", precision = 3, scale = 0)
	public Short getBclrRed() {
		return this.bclrRed;
	}

	public void setBclrRed(Short bclrRed) {
		this.bclrRed = bclrRed;
	}

	@Column(name = "BCLR_GREEN", precision = 3, scale = 0)
	public Short getBclrGreen() {
		return this.bclrGreen;
	}

	public void setBclrGreen(Short bclrGreen) {
		this.bclrGreen = bclrGreen;
	}

	@Column(name = "BCLR_BLUE", precision = 3, scale = 0)
	public Short getBclrBlue() {
		return this.bclrBlue;
	}

	public void setBclrBlue(Short bclrBlue) {
		this.bclrBlue = bclrBlue;
	}

	@Column(name = "FCLR_RED", precision = 3, scale = 0)
	public Short getFclrRed() {
		return this.fclrRed;
	}

	public void setFclrRed(Short fclrRed) {
		this.fclrRed = fclrRed;
	}

	@Column(name = "FCLR_GREEN", precision = 3, scale = 0)
	public Short getFclrGreen() {
		return this.fclrGreen;
	}

	public void setFclrGreen(Short fclrGreen) {
		this.fclrGreen = fclrGreen;
	}

	@Column(name = "FCLR_BLUE", precision = 3, scale = 0)
	public Short getFclrBlue() {
		return this.fclrBlue;
	}

	public void setFclrBlue(Short fclrBlue) {
		this.fclrBlue = fclrBlue;
	}

	@Column(name = "ADD_USER", length = 10)
	public String getAddUser() {
		return this.addUser;
	}

	public void setAddUser(String addUser) {
		this.addUser = addUser;
	}

	@Column(name = "ADD_PC", length = 30)
	public String getAddPc() {
		return this.addPc;
	}

	public void setAddPc(String addPc) {
		this.addPc = addPc;
	}

	@Column(name = "ADD_DATE", precision = 8, scale = 0)
	public Integer getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Integer addDate) {
		this.addDate = addDate;
	}

	@Column(name = "ADD_TIME", precision = 6, scale = 0)
	public Integer getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Integer addTime) {
		this.addTime = addTime;
	}

	@Column(name = "LASTUP_USER", length = 10)
	public String getLastupUser() {
		return this.lastupUser;
	}

	public void setLastupUser(String lastupUser) {
		this.lastupUser = lastupUser;
	}

	@Column(name = "LASTUP_PC", length = 30)
	public String getLastupPc() {
		return this.lastupPc;
	}

	public void setLastupPc(String lastupPc) {
		this.lastupPc = lastupPc;
	}

	@Column(name = "LASTUP_DATE", precision = 8, scale = 0)
	public Integer getLastupDate() {
		return this.lastupDate;
	}

	public void setLastupDate(Integer lastupDate) {
		this.lastupDate = lastupDate;
	}

	@Column(name = "LASTUP_TIME", precision = 6, scale = 0)
	public Integer getLastupTime() {
		return this.lastupTime;
	}

	public void setLastupTime(Integer lastupTime) {
		this.lastupTime = lastupTime;
	}

}
