package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MColorcls generated by hbm2java
 */
@Entity
@Table(name = "M_COLORCLS", schema = "DB2ADMIN")
public class MColorcls implements java.io.Serializable {

	private String colorclsCode;
	private String colorclsName;
	private String help;
	private Character useFlg;
	private String dspSeq;

	public MColorcls() {
	}

	public MColorcls(String colorclsCode) {
		this.colorclsCode = colorclsCode;
	}

	public MColorcls(String colorclsCode, String colorclsName, String help,
			Character useFlg, String dspSeq) {
		this.colorclsCode = colorclsCode;
		this.colorclsName = colorclsName;
		this.help = help;
		this.useFlg = useFlg;
		this.dspSeq = dspSeq;
	}

	@Id
	@Column(name = "COLORCLS_CODE", unique = true, nullable = false, length = 8)
	public String getColorclsCode() {
		return this.colorclsCode;
	}

	public void setColorclsCode(String colorclsCode) {
		this.colorclsCode = colorclsCode;
	}

	@Column(name = "COLORCLS_NAME", length = 24)
	public String getColorclsName() {
		return this.colorclsName;
	}

	public void setColorclsName(String colorclsName) {
		this.colorclsName = colorclsName;
	}

	@Column(name = "HELP", length = 100)
	public String getHelp() {
		return this.help;
	}

	public void setHelp(String help) {
		this.help = help;
	}

	@Column(name = "USE_FLG", length = 1)
	public Character getUseFlg() {
		return this.useFlg;
	}

	public void setUseFlg(Character useFlg) {
		this.useFlg = useFlg;
	}

	@Column(name = "DSP_SEQ", length = 3)
	public String getDspSeq() {
		return this.dspSeq;
	}

	public void setDspSeq(String dspSeq) {
		this.dspSeq = dspSeq;
	}

}
