package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MColorId generated by hbm2java
 */
@Embeddable
public class MColorId implements java.io.Serializable {

	private String colorclsCode;
	private String colorCode;

	public MColorId() {
	}

	public MColorId(String colorclsCode, String colorCode) {
		this.colorclsCode = colorclsCode;
		this.colorCode = colorCode;
	}

	@Column(name = "COLORCLS_CODE", nullable = false, length = 8)
	public String getColorclsCode() {
		return this.colorclsCode;
	}

	public void setColorclsCode(String colorclsCode) {
		this.colorclsCode = colorclsCode;
	}

	@Column(name = "COLOR_CODE", nullable = false, length = 2)
	public String getColorCode() {
		return this.colorCode;
	}

	public void setColorCode(String colorCode) {
		this.colorCode = colorCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MColorId))
			return false;
		MColorId castOther = (MColorId) other;

		return ((this.getColorclsCode() == castOther.getColorclsCode()) || (this
				.getColorclsCode() != null
				&& castOther.getColorclsCode() != null && this
				.getColorclsCode().equals(castOther.getColorclsCode())))
				&& ((this.getColorCode() == castOther.getColorCode()) || (this
						.getColorCode() != null
						&& castOther.getColorCode() != null && this
						.getColorCode().equals(castOther.getColorCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getColorclsCode() == null ? 0 : this.getColorclsCode()
						.hashCode());
		result = 37 * result
				+ (getColorCode() == null ? 0 : this.getColorCode().hashCode());
		return result;
	}

}
