package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MCtlId generated by hbm2java
 */
@Embeddable
public class MCtlId implements java.io.Serializable {

	private String userid;
	private String CKey;

	public MCtlId() {
	}

	public MCtlId(String userid, String CKey) {
		this.userid = userid;
		this.CKey = CKey;
	}

	@Column(name = "USERID", nullable = false, length = 10)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "C_KEY", nullable = false, length = 8)
	public String getCKey() {
		return this.CKey;
	}

	public void setCKey(String CKey) {
		this.CKey = CKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MCtlId))
			return false;
		MCtlId castOther = (MCtlId) other;

		return ((this.getUserid() == castOther.getUserid()) || (this
				.getUserid() != null && castOther.getUserid() != null && this
				.getUserid().equals(castOther.getUserid())))
				&& ((this.getCKey() == castOther.getCKey()) || (this.getCKey() != null
						&& castOther.getCKey() != null && this.getCKey()
						.equals(castOther.getCKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result
				+ (getCKey() == null ? 0 : this.getCKey().hashCode());
		return result;
	}

}
