package dao.model;

// Generated Sep 21, 2011 11:28:32 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MEmp generated by hbm2java
 */
@Entity
@Table(name = "M_EMP", schema = "DB2ADMIN")
public class MEmp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String empCode;
	private String empKana;
	private String empName;
	private String empTname;
	private String userUser;
	private String empUser;
	private String pwd;
	private Integer dsporderNo;
	private Character inoutFlg;
	private String telno;
	private String mailadr;
	private String mailadrm;
	private String sectCode;
	private Character sect1Code;
	private String sect2Code;
	private String sect3Code;
	private String sect4Code;
	private String emptyp1Code;
	private String emptyp2Code;
	private String emptyp3Code;
	private String pcid;
	private Character logviewFlg;
	private Character excelout;
	private String pathName;
	private String oldCode;
	private String searchidx;
	private Character usingFlg;
	private Character useFlg;
	private Integer pwdDate;
	private String pwd1;
	private String pwd2;
	private String pwd3;
	private String addUser;
	private String addPc;
	private Integer addDate;
	private Integer addTime;
	private String lastupUser;
	private String lastupPc;
	private Integer lastupDate;
	private Integer lastupTime;

	public MEmp() {
	}

	public MEmp(String empCode) {
		this.empCode = empCode;
	}

	public MEmp(String empCode, String empKana, String empName,
			String empTname, String userUser, String empUser, String pwd,
			Integer dsporderNo, Character inoutFlg, String telno,
			String mailadr, String mailadrm, String sectCode,
			Character sect1Code, String sect2Code, String sect3Code,
			String sect4Code, String emptyp1Code, String emptyp2Code,
			String emptyp3Code, String pcid, Character logviewFlg,
			Character excelout, String pathName, String oldCode,
			String searchidx, Character usingFlg, Character useFlg,
			Integer pwdDate, String pwd1, String pwd2, String pwd3,
			String addUser, String addPc, Integer addDate, Integer addTime,
			String lastupUser, String lastupPc, Integer lastupDate,
			Integer lastupTime) {
		this.empCode = empCode;
		this.empKana = empKana;
		this.empName = empName;
		this.empTname = empTname;
		this.userUser = userUser;
		this.empUser = empUser;
		this.pwd = pwd;
		this.dsporderNo = dsporderNo;
		this.inoutFlg = inoutFlg;
		this.telno = telno;
		this.mailadr = mailadr;
		this.mailadrm = mailadrm;
		this.sectCode = sectCode;
		this.sect1Code = sect1Code;
		this.sect2Code = sect2Code;
		this.sect3Code = sect3Code;
		this.sect4Code = sect4Code;
		this.emptyp1Code = emptyp1Code;
		this.emptyp2Code = emptyp2Code;
		this.emptyp3Code = emptyp3Code;
		this.pcid = pcid;
		this.logviewFlg = logviewFlg;
		this.excelout = excelout;
		this.pathName = pathName;
		this.oldCode = oldCode;
		this.searchidx = searchidx;
		this.usingFlg = usingFlg;
		this.useFlg = useFlg;
		this.pwdDate = pwdDate;
		this.pwd1 = pwd1;
		this.pwd2 = pwd2;
		this.pwd3 = pwd3;
		this.addUser = addUser;
		this.addPc = addPc;
		this.addDate = addDate;
		this.addTime = addTime;
		this.lastupUser = lastupUser;
		this.lastupPc = lastupPc;
		this.lastupDate = lastupDate;
		this.lastupTime = lastupTime;
	}

	@Id
	@Column(name = "EMP_CODE", unique = true, nullable = false, length = 6)
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Column(name = "EMP_KANA", length = 20)
	public String getEmpKana() {
		return this.empKana;
	}

	public void setEmpKana(String empKana) {
		this.empKana = empKana;
	}

	@Column(name = "EMP_NAME", length = 24)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "EMP_TNAME", length = 12)
	public String getEmpTname() {
		return this.empTname;
	}

	public void setEmpTname(String empTname) {
		this.empTname = empTname;
	}

	@Column(name = "USER_USER", length = 10)
	public String getUserUser() {
		return this.userUser;
	}

	public void setUserUser(String userUser) {
		this.userUser = userUser;
	}

	@Column(name = "EMP_USER", length = 10)
	public String getEmpUser() {
		return this.empUser;
	}

	public void setEmpUser(String empUser) {
		this.empUser = empUser;
	}

	@Column(name = "PWD", length = 16)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "DSPORDER_NO", precision = 6, scale = 0)
	public Integer getDsporderNo() {
		return this.dsporderNo;
	}

	public void setDsporderNo(Integer dsporderNo) {
		this.dsporderNo = dsporderNo;
	}

	@Column(name = "INOUT_FLG", length = 1)
	public Character getInoutFlg() {
		return this.inoutFlg;
	}

	public void setInoutFlg(Character inoutFlg) {
		this.inoutFlg = inoutFlg;
	}

	@Column(name = "TELNO", length = 17)
	public String getTelno() {
		return this.telno;
	}

	public void setTelno(String telno) {
		this.telno = telno;
	}

	@Column(name = "MAILADR", length = 50)
	public String getMailadr() {
		return this.mailadr;
	}

	public void setMailadr(String mailadr) {
		this.mailadr = mailadr;
	}

	@Column(name = "MAILADRM", length = 50)
	public String getMailadrm() {
		return this.mailadrm;
	}

	public void setMailadrm(String mailadrm) {
		this.mailadrm = mailadrm;
	}

	@Column(name = "SECT_CODE", length = 3)
	public String getSectCode() {
		return this.sectCode;
	}

	public void setSectCode(String sectCode) {
		this.sectCode = sectCode;
	}

	@Column(name = "SECT1_CODE", length = 1)
	public Character getSect1Code() {
		return this.sect1Code;
	}

	public void setSect1Code(Character sect1Code) {
		this.sect1Code = sect1Code;
	}

	@Column(name = "SECT2_CODE", length = 2)
	public String getSect2Code() {
		return this.sect2Code;
	}

	public void setSect2Code(String sect2Code) {
		this.sect2Code = sect2Code;
	}

	@Column(name = "SECT3_CODE", length = 3)
	public String getSect3Code() {
		return this.sect3Code;
	}

	public void setSect3Code(String sect3Code) {
		this.sect3Code = sect3Code;
	}

	@Column(name = "SECT4_CODE", length = 2)
	public String getSect4Code() {
		return this.sect4Code;
	}

	public void setSect4Code(String sect4Code) {
		this.sect4Code = sect4Code;
	}

	@Column(name = "EMPTYP1_CODE", length = 3)
	public String getEmptyp1Code() {
		return this.emptyp1Code;
	}

	public void setEmptyp1Code(String emptyp1Code) {
		this.emptyp1Code = emptyp1Code;
	}

	@Column(name = "EMPTYP2_CODE", length = 3)
	public String getEmptyp2Code() {
		return this.emptyp2Code;
	}

	public void setEmptyp2Code(String emptyp2Code) {
		this.emptyp2Code = emptyp2Code;
	}

	@Column(name = "EMPTYP3_CODE", length = 3)
	public String getEmptyp3Code() {
		return this.emptyp3Code;
	}

	public void setEmptyp3Code(String emptyp3Code) {
		this.emptyp3Code = emptyp3Code;
	}

	@Column(name = "PCID", length = 30)
	public String getPcid() {
		return this.pcid;
	}

	public void setPcid(String pcid) {
		this.pcid = pcid;
	}

	@Column(name = "LOGVIEW_FLG", length = 1)
	public Character getLogviewFlg() {
		return this.logviewFlg;
	}

	public void setLogviewFlg(Character logviewFlg) {
		this.logviewFlg = logviewFlg;
	}

	@Column(name = "EXCELOUT", length = 1)
	public Character getExcelout() {
		return this.excelout;
	}

	public void setExcelout(Character excelout) {
		this.excelout = excelout;
	}

	@Column(name = "PATH_NAME", length = 200)
	public String getPathName() {
		return this.pathName;
	}

	public void setPathName(String pathName) {
		this.pathName = pathName;
	}

	@Column(name = "OLD_CODE", length = 20)
	public String getOldCode() {
		return this.oldCode;
	}

	public void setOldCode(String oldCode) {
		this.oldCode = oldCode;
	}

	@Column(name = "SEARCHIDX", length = 2)
	public String getSearchidx() {
		return this.searchidx;
	}

	public void setSearchidx(String searchidx) {
		this.searchidx = searchidx;
	}

	@Column(name = "USING_FLG", length = 1)
	public Character getUsingFlg() {
		return this.usingFlg;
	}

	public void setUsingFlg(Character usingFlg) {
		this.usingFlg = usingFlg;
	}

	@Column(name = "USE_FLG", length = 1)
	public Character getUseFlg() {
		return this.useFlg;
	}

	public void setUseFlg(Character useFlg) {
		this.useFlg = useFlg;
	}

	@Column(name = "PWD_DATE", precision = 8, scale = 0)
	public Integer getPwdDate() {
		return this.pwdDate;
	}

	public void setPwdDate(Integer pwdDate) {
		this.pwdDate = pwdDate;
	}

	@Column(name = "PWD1", length = 16)
	public String getPwd1() {
		return this.pwd1;
	}

	public void setPwd1(String pwd1) {
		this.pwd1 = pwd1;
	}

	@Column(name = "PWD2", length = 16)
	public String getPwd2() {
		return this.pwd2;
	}

	public void setPwd2(String pwd2) {
		this.pwd2 = pwd2;
	}

	@Column(name = "PWD3", length = 16)
	public String getPwd3() {
		return this.pwd3;
	}

	public void setPwd3(String pwd3) {
		this.pwd3 = pwd3;
	}

	@Column(name = "ADD_USER", length = 10)
	public String getAddUser() {
		return this.addUser;
	}

	public void setAddUser(String addUser) {
		this.addUser = addUser;
	}

	@Column(name = "ADD_PC", length = 30)
	public String getAddPc() {
		return this.addPc;
	}

	public void setAddPc(String addPc) {
		this.addPc = addPc;
	}

	@Column(name = "ADD_DATE", precision = 8, scale = 0)
	public Integer getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Integer addDate) {
		this.addDate = addDate;
	}

	@Column(name = "ADD_TIME", precision = 6, scale = 0)
	public Integer getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Integer addTime) {
		this.addTime = addTime;
	}

	@Column(name = "LASTUP_USER", length = 10)
	public String getLastupUser() {
		return this.lastupUser;
	}

	public void setLastupUser(String lastupUser) {
		this.lastupUser = lastupUser;
	}

	@Column(name = "LASTUP_PC", length = 30)
	public String getLastupPc() {
		return this.lastupPc;
	}

	public void setLastupPc(String lastupPc) {
		this.lastupPc = lastupPc;
	}

	@Column(name = "LASTUP_DATE", precision = 8, scale = 0)
	public Integer getLastupDate() {
		return this.lastupDate;
	}

	public void setLastupDate(Integer lastupDate) {
		this.lastupDate = lastupDate;
	}

	@Column(name = "LASTUP_TIME", precision = 6, scale = 0)
	public Integer getLastupTime() {
		return this.lastupTime;
	}

	public void setLastupTime(Integer lastupTime) {
		this.lastupTime = lastupTime;
	}

}
