package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MMdelchk generated by hbm2java
 */
@Entity
@Table(name = "M_MDELCHK", schema = "DB2ADMIN")
public class MMdelchk implements java.io.Serializable {

	private MMdelchkId id;
	private String tableName;
	private String whereFld1;
	private String whereFld2;
	private String whereFld3;
	private String whereFld4;
	private String whereFld5;
	private String whereFld6;
	private String whereFld7;
	private String whereFld8;
	private String whereFld9;
	private String whereFld10;

	public MMdelchk() {
	}

	public MMdelchk(MMdelchkId id) {
		this.id = id;
	}

	public MMdelchk(MMdelchkId id, String tableName, String whereFld1,
			String whereFld2, String whereFld3, String whereFld4,
			String whereFld5, String whereFld6, String whereFld7,
			String whereFld8, String whereFld9, String whereFld10) {
		this.id = id;
		this.tableName = tableName;
		this.whereFld1 = whereFld1;
		this.whereFld2 = whereFld2;
		this.whereFld3 = whereFld3;
		this.whereFld4 = whereFld4;
		this.whereFld5 = whereFld5;
		this.whereFld6 = whereFld6;
		this.whereFld7 = whereFld7;
		this.whereFld8 = whereFld8;
		this.whereFld9 = whereFld9;
		this.whereFld10 = whereFld10;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "menugrpCode", column = @Column(name = "MENUGRP_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "menuexeCode", column = @Column(name = "MENUEXE_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "exeNo", column = @Column(name = "EXE_NO", nullable = false, length = 1)),
			@AttributeOverride(name = "seqNo", column = @Column(name = "SEQ_NO", nullable = false, precision = 2, scale = 0)) })
	public MMdelchkId getId() {
		return this.id;
	}

	public void setId(MMdelchkId id) {
		this.id = id;
	}

	@Column(name = "TABLE_NAME", length = 20)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "WHERE_FLD1", length = 20)
	public String getWhereFld1() {
		return this.whereFld1;
	}

	public void setWhereFld1(String whereFld1) {
		this.whereFld1 = whereFld1;
	}

	@Column(name = "WHERE_FLD2", length = 20)
	public String getWhereFld2() {
		return this.whereFld2;
	}

	public void setWhereFld2(String whereFld2) {
		this.whereFld2 = whereFld2;
	}

	@Column(name = "WHERE_FLD3", length = 20)
	public String getWhereFld3() {
		return this.whereFld3;
	}

	public void setWhereFld3(String whereFld3) {
		this.whereFld3 = whereFld3;
	}

	@Column(name = "WHERE_FLD4", length = 20)
	public String getWhereFld4() {
		return this.whereFld4;
	}

	public void setWhereFld4(String whereFld4) {
		this.whereFld4 = whereFld4;
	}

	@Column(name = "WHERE_FLD5", length = 20)
	public String getWhereFld5() {
		return this.whereFld5;
	}

	public void setWhereFld5(String whereFld5) {
		this.whereFld5 = whereFld5;
	}

	@Column(name = "WHERE_FLD6", length = 20)
	public String getWhereFld6() {
		return this.whereFld6;
	}

	public void setWhereFld6(String whereFld6) {
		this.whereFld6 = whereFld6;
	}

	@Column(name = "WHERE_FLD7", length = 20)
	public String getWhereFld7() {
		return this.whereFld7;
	}

	public void setWhereFld7(String whereFld7) {
		this.whereFld7 = whereFld7;
	}

	@Column(name = "WHERE_FLD8", length = 20)
	public String getWhereFld8() {
		return this.whereFld8;
	}

	public void setWhereFld8(String whereFld8) {
		this.whereFld8 = whereFld8;
	}

	@Column(name = "WHERE_FLD9", length = 20)
	public String getWhereFld9() {
		return this.whereFld9;
	}

	public void setWhereFld9(String whereFld9) {
		this.whereFld9 = whereFld9;
	}

	@Column(name = "WHERE_FLD10", length = 20)
	public String getWhereFld10() {
		return this.whereFld10;
	}

	public void setWhereFld10(String whereFld10) {
		this.whereFld10 = whereFld10;
	}

}
