package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MMdelchkId generated by hbm2java
 */
@Embeddable
public class MMdelchkId implements java.io.Serializable {

	private String menugrpCode;
	private String menuexeCode;
	private char exeNo;
	private byte seqNo;

	public MMdelchkId() {
	}

	public MMdelchkId(String menugrpCode, String menuexeCode, char exeNo,
			byte seqNo) {
		this.menugrpCode = menugrpCode;
		this.menuexeCode = menuexeCode;
		this.exeNo = exeNo;
		this.seqNo = seqNo;
	}

	@Column(name = "MENUGRP_CODE", nullable = false, length = 3)
	public String getMenugrpCode() {
		return this.menugrpCode;
	}

	public void setMenugrpCode(String menugrpCode) {
		this.menugrpCode = menugrpCode;
	}

	@Column(name = "MENUEXE_CODE", nullable = false, length = 3)
	public String getMenuexeCode() {
		return this.menuexeCode;
	}

	public void setMenuexeCode(String menuexeCode) {
		this.menuexeCode = menuexeCode;
	}

	@Column(name = "EXE_NO", nullable = false, length = 1)
	public char getExeNo() {
		return this.exeNo;
	}

	public void setExeNo(char exeNo) {
		this.exeNo = exeNo;
	}

	@Column(name = "SEQ_NO", nullable = false, precision = 2, scale = 0)
	public byte getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(byte seqNo) {
		this.seqNo = seqNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MMdelchkId))
			return false;
		MMdelchkId castOther = (MMdelchkId) other;

		return ((this.getMenugrpCode() == castOther.getMenugrpCode()) || (this
				.getMenugrpCode() != null && castOther.getMenugrpCode() != null && this
				.getMenugrpCode().equals(castOther.getMenugrpCode())))
				&& ((this.getMenuexeCode() == castOther.getMenuexeCode()) || (this
						.getMenuexeCode() != null
						&& castOther.getMenuexeCode() != null && this
						.getMenuexeCode().equals(castOther.getMenuexeCode())))
				&& (this.getExeNo() == castOther.getExeNo())
				&& (this.getSeqNo() == castOther.getSeqNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMenugrpCode() == null ? 0 : this.getMenugrpCode()
						.hashCode());
		result = 37
				* result
				+ (getMenuexeCode() == null ? 0 : this.getMenuexeCode()
						.hashCode());
		result = 37 * result + this.getExeNo();
		result = 37 * result + this.getSeqNo();
		return result;
	}

}
