package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MMenurptId generated by hbm2java
 */
@Embeddable
public class MMenurptId implements java.io.Serializable {

	private String menugrpCode;
	private String menuexeCode;

	public MMenurptId() {
	}

	public MMenurptId(String menugrpCode, String menuexeCode) {
		this.menugrpCode = menugrpCode;
		this.menuexeCode = menuexeCode;
	}

	@Column(name = "MENUGRP_CODE", nullable = false, length = 3)
	public String getMenugrpCode() {
		return this.menugrpCode;
	}

	public void setMenugrpCode(String menugrpCode) {
		this.menugrpCode = menugrpCode;
	}

	@Column(name = "MENUEXE_CODE", nullable = false, length = 3)
	public String getMenuexeCode() {
		return this.menuexeCode;
	}

	public void setMenuexeCode(String menuexeCode) {
		this.menuexeCode = menuexeCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MMenurptId))
			return false;
		MMenurptId castOther = (MMenurptId) other;

		return ((this.getMenugrpCode() == castOther.getMenugrpCode()) || (this
				.getMenugrpCode() != null && castOther.getMenugrpCode() != null && this
				.getMenugrpCode().equals(castOther.getMenugrpCode())))
				&& ((this.getMenuexeCode() == castOther.getMenuexeCode()) || (this
						.getMenuexeCode() != null
						&& castOther.getMenuexeCode() != null && this
						.getMenuexeCode().equals(castOther.getMenuexeCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMenugrpCode() == null ? 0 : this.getMenugrpCode()
						.hashCode());
		result = 37
				* result
				+ (getMenuexeCode() == null ? 0 : this.getMenuexeCode()
						.hashCode());
		return result;
	}

}
