package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MMenuexe generated by hbm2java
 */
@Entity
@Table(name = "M_MENUEXE", schema = "DB2ADMIN")
public class MMenuexe implements java.io.Serializable {

	private MMenuexeId id;
	private String menuexeName;
	private String menuexeHelp;
	private Character funType;
	private String className;
	private String pathName;
	private String menuexeSeq;

	public MMenuexe() {
	}

	public MMenuexe(MMenuexeId id) {
		this.id = id;
	}

	public MMenuexe(MMenuexeId id, String menuexeName, String menuexeHelp,
			Character funType, String className, String pathName,
			String menuexeSeq) {
		this.id = id;
		this.menuexeName = menuexeName;
		this.menuexeHelp = menuexeHelp;
		this.funType = funType;
		this.className = className;
		this.pathName = pathName;
		this.menuexeSeq = menuexeSeq;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "menugrpCode", column = @Column(name = "MENUGRP_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "menuexeCode", column = @Column(name = "MENUEXE_CODE", nullable = false, length = 3)) })
	public MMenuexeId getId() {
		return this.id;
	}

	public void setId(MMenuexeId id) {
		this.id = id;
	}

	@Column(name = "MENUEXE_NAME", length = 42)
	public String getMenuexeName() {
		return this.menuexeName;
	}

	public void setMenuexeName(String menuexeName) {
		this.menuexeName = menuexeName;
	}

	@Column(name = "MENUEXE_HELP", length = 300)
	public String getMenuexeHelp() {
		return this.menuexeHelp;
	}

	public void setMenuexeHelp(String menuexeHelp) {
		this.menuexeHelp = menuexeHelp;
	}

	@Column(name = "FUN_TYPE", length = 1)
	public Character getFunType() {
		return this.funType;
	}

	public void setFunType(Character funType) {
		this.funType = funType;
	}

	@Column(name = "CLASS_NAME", length = 200)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "PATH_NAME", length = 200)
	public String getPathName() {
		return this.pathName;
	}

	public void setPathName(String pathName) {
		this.pathName = pathName;
	}

	@Column(name = "MENUEXE_SEQ", length = 3)
	public String getMenuexeSeq() {
		return this.menuexeSeq;
	}

	public void setMenuexeSeq(String menuexeSeq) {
		this.menuexeSeq = menuexeSeq;
	}

}
