package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MMenurpt generated by hbm2java
 */
@Entity
@Table(name = "M_MENURPT", schema = "DB2ADMIN")
public class MMenurpt implements java.io.Serializable {

	private MMenurptId id;
	private Short dsporderNo;
	private String prtCtl;

	public MMenurpt() {
	}

	public MMenurpt(MMenurptId id) {
		this.id = id;
	}

	public MMenurpt(MMenurptId id, Short dsporderNo, String prtCtl) {
		this.id = id;
		this.dsporderNo = dsporderNo;
		this.prtCtl = prtCtl;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "menugrpCode", column = @Column(name = "MENUGRP_CODE", nullable = false, length = 3)),
			@AttributeOverride(name = "menuexeCode", column = @Column(name = "MENUEXE_CODE", nullable = false, length = 3)) })
	public MMenurptId getId() {
		return this.id;
	}

	public void setId(MMenurptId id) {
		this.id = id;
	}

	@Column(name = "DSPORDER_NO", precision = 3, scale = 0)
	public Short getDsporderNo() {
		return this.dsporderNo;
	}

	public void setDsporderNo(Short dsporderNo) {
		this.dsporderNo = dsporderNo;
	}

	@Column(name = "PRT_CTL", length = 8)
	public String getPrtCtl() {
		return this.prtCtl;
	}

	public void setPrtCtl(String prtCtl) {
		this.prtCtl = prtCtl;
	}

}
