package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MMsg generated by hbm2java
 */
@Entity
@Table(name = "M_MSG", schema = "DB2ADMIN")
public class MMsg implements java.io.Serializable {

	private String msgCd;
	private String msg1;
	private String msg2;
	private String msg3;
	private String msg4;
	private Character buttonType;

	public MMsg() {
	}

	public MMsg(String msgCd) {
		this.msgCd = msgCd;
	}

	public MMsg(String msgCd, String msg1, String msg2, String msg3,
			String msg4, Character buttonType) {
		this.msgCd = msgCd;
		this.msg1 = msg1;
		this.msg2 = msg2;
		this.msg3 = msg3;
		this.msg4 = msg4;
		this.buttonType = buttonType;
	}

	@Id
	@Column(name = "MSG_CD", unique = true, nullable = false, length = 5)
	public String getMsgCd() {
		return this.msgCd;
	}

	public void setMsgCd(String msgCd) {
		this.msgCd = msgCd;
	}

	@Column(name = "MSG1", length = 50)
	public String getMsg1() {
		return this.msg1;
	}

	public void setMsg1(String msg1) {
		this.msg1 = msg1;
	}

	@Column(name = "MSG2", length = 50)
	public String getMsg2() {
		return this.msg2;
	}

	public void setMsg2(String msg2) {
		this.msg2 = msg2;
	}

	@Column(name = "MSG3", length = 50)
	public String getMsg3() {
		return this.msg3;
	}

	public void setMsg3(String msg3) {
		this.msg3 = msg3;
	}

	@Column(name = "MSG4", length = 50)
	public String getMsg4() {
		return this.msg4;
	}

	public void setMsg4(String msg4) {
		this.msg4 = msg4;
	}

	@Column(name = "BUTTON_TYPE", length = 1)
	public Character getButtonType() {
		return this.buttonType;
	}

	public void setButtonType(Character buttonType) {
		this.buttonType = buttonType;
	}

}
