package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MMymenuGId generated by hbm2java
 */
@Embeddable
public class MMymenuGId implements java.io.Serializable {

	private String usergid;
	private String menuexeSeq;

	public MMymenuGId() {
	}

	public MMymenuGId(String usergid, String menuexeSeq) {
		this.usergid = usergid;
		this.menuexeSeq = menuexeSeq;
	}

	@Column(name = "USERGID", nullable = false, length = 10)
	public String getUsergid() {
		return this.usergid;
	}

	public void setUsergid(String usergid) {
		this.usergid = usergid;
	}

	@Column(name = "MENUEXE_SEQ", nullable = false, length = 3)
	public String getMenuexeSeq() {
		return this.menuexeSeq;
	}

	public void setMenuexeSeq(String menuexeSeq) {
		this.menuexeSeq = menuexeSeq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MMymenuGId))
			return false;
		MMymenuGId castOther = (MMymenuGId) other;

		return ((this.getUsergid() == castOther.getUsergid()) || (this
				.getUsergid() != null && castOther.getUsergid() != null && this
				.getUsergid().equals(castOther.getUsergid())))
				&& ((this.getMenuexeSeq() == castOther.getMenuexeSeq()) || (this
						.getMenuexeSeq() != null
						&& castOther.getMenuexeSeq() != null && this
						.getMenuexeSeq().equals(castOther.getMenuexeSeq())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsergid() == null ? 0 : this.getUsergid().hashCode());
		result = 37
				* result
				+ (getMenuexeSeq() == null ? 0 : this.getMenuexeSeq()
						.hashCode());
		return result;
	}

}
