package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MMymenuId generated by hbm2java
 */
@Embeddable
public class MMymenuId implements java.io.Serializable {

	private String userid;
	private String menuexeSeq;

	public MMymenuId() {
	}

	public MMymenuId(String userid, String menuexeSeq) {
		this.userid = userid;
		this.menuexeSeq = menuexeSeq;
	}

	@Column(name = "USERID", nullable = false, length = 10)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "MENUEXE_SEQ", nullable = false, length = 3)
	public String getMenuexeSeq() {
		return this.menuexeSeq;
	}

	public void setMenuexeSeq(String menuexeSeq) {
		this.menuexeSeq = menuexeSeq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MMymenuId))
			return false;
		MMymenuId castOther = (MMymenuId) other;

		return ((this.getUserid() == castOther.getUserid()) || (this
				.getUserid() != null && castOther.getUserid() != null && this
				.getUserid().equals(castOther.getUserid())))
				&& ((this.getMenuexeSeq() == castOther.getMenuexeSeq()) || (this
						.getMenuexeSeq() != null
						&& castOther.getMenuexeSeq() != null && this
						.getMenuexeSeq().equals(castOther.getMenuexeSeq())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37
				* result
				+ (getMenuexeSeq() == null ? 0 : this.getMenuexeSeq()
						.hashCode());
		return result;
	}

}
