package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MNameId generated by hbm2java
 */
@Embeddable
public class MNameId implements java.io.Serializable {

	private String nameclsCode;
	private String nameCode;

	public MNameId() {
	}

	public MNameId(String nameclsCode, String nameCode) {
		this.nameclsCode = nameclsCode;
		this.nameCode = nameCode;
	}

	@Column(name = "NAMECLS_CODE", nullable = false, length = 8)
	public String getNameclsCode() {
		return this.nameclsCode;
	}

	public void setNameclsCode(String nameclsCode) {
		this.nameclsCode = nameclsCode;
	}

	@Column(name = "NAME_CODE", nullable = false, length = 5)
	public String getNameCode() {
		return this.nameCode;
	}

	public void setNameCode(String nameCode) {
		this.nameCode = nameCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MNameId))
			return false;
		MNameId castOther = (MNameId) other;

		return ((this.getNameclsCode() == castOther.getNameclsCode()) || (this
				.getNameclsCode() != null && castOther.getNameclsCode() != null && this
				.getNameclsCode().equals(castOther.getNameclsCode())))
				&& ((this.getNameCode() == castOther.getNameCode()) || (this
						.getNameCode() != null
						&& castOther.getNameCode() != null && this
						.getNameCode().equals(castOther.getNameCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNameclsCode() == null ? 0 : this.getNameclsCode()
						.hashCode());
		result = 37 * result
				+ (getNameCode() == null ? 0 : this.getNameCode().hashCode());
		return result;
	}

}
