package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MNamecls generated by hbm2java
 */
@Entity
@Table(name = "M_NAMECLS", schema = "DB2ADMIN")
public class MNamecls implements java.io.Serializable {

	private String nameclsCode;
	private String nameclsName;
	private String help;
	private Character useFlg;
	private String dspSeq;

	public MNamecls() {
	}

	public MNamecls(String nameclsCode) {
		this.nameclsCode = nameclsCode;
	}

	public MNamecls(String nameclsCode, String nameclsName, String help,
			Character useFlg, String dspSeq) {
		this.nameclsCode = nameclsCode;
		this.nameclsName = nameclsName;
		this.help = help;
		this.useFlg = useFlg;
		this.dspSeq = dspSeq;
	}

	@Id
	@Column(name = "NAMECLS_CODE", unique = true, nullable = false, length = 8)
	public String getNameclsCode() {
		return this.nameclsCode;
	}

	public void setNameclsCode(String nameclsCode) {
		this.nameclsCode = nameclsCode;
	}

	@Column(name = "NAMECLS_NAME", length = 24)
	public String getNameclsName() {
		return this.nameclsName;
	}

	public void setNameclsName(String nameclsName) {
		this.nameclsName = nameclsName;
	}

	@Column(name = "HELP", length = 100)
	public String getHelp() {
		return this.help;
	}

	public void setHelp(String help) {
		this.help = help;
	}

	@Column(name = "USE_FLG", length = 1)
	public Character getUseFlg() {
		return this.useFlg;
	}

	public void setUseFlg(Character useFlg) {
		this.useFlg = useFlg;
	}

	@Column(name = "DSP_SEQ", length = 3)
	public String getDspSeq() {
		return this.dspSeq;
	}

	public void setDspSeq(String dspSeq) {
		this.dspSeq = dspSeq;
	}

}
