package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MName generated by hbm2java
 */
@Entity
@Table(name = "M_NAME", schema = "DB2ADMIN")
public class MName implements java.io.Serializable {

	private MNameId id;
	private String nameName;
	private String nameRname;
	private String namePname;
	private String nameTname;
	private Character defaultType;
	private Character dspFlg;
	private Short dsporderNo;
	private Character nametype;
	private String addUser;
	private String addPc;
	private Integer addDate;
	private Integer addTime;
	private String lastupUser;
	private String lastupPc;
	private Integer lastupDate;
	private Integer lastupTime;

	public MName() {
	}

	public MName(MNameId id) {
		this.id = id;
	}

	public MName(MNameId id, String nameName, String nameRname,
			String namePname, String nameTname, Character defaultType,
			Character dspFlg, Short dsporderNo, Character nametype,
			String addUser, String addPc, Integer addDate, Integer addTime,
			String lastupUser, String lastupPc, Integer lastupDate,
			Integer lastupTime) {
		this.id = id;
		this.nameName = nameName;
		this.nameRname = nameRname;
		this.namePname = namePname;
		this.nameTname = nameTname;
		this.defaultType = defaultType;
		this.dspFlg = dspFlg;
		this.dsporderNo = dsporderNo;
		this.nametype = nametype;
		this.addUser = addUser;
		this.addPc = addPc;
		this.addDate = addDate;
		this.addTime = addTime;
		this.lastupUser = lastupUser;
		this.lastupPc = lastupPc;
		this.lastupDate = lastupDate;
		this.lastupTime = lastupTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nameclsCode", column = @Column(name = "NAMECLS_CODE", nullable = false, length = 8)),
			@AttributeOverride(name = "nameCode", column = @Column(name = "NAME_CODE", nullable = false, length = 5)) })
	public MNameId getId() {
		return this.id;
	}

	public void setId(MNameId id) {
		this.id = id;
	}

	@Column(name = "NAME_NAME", length = 40)
	public String getNameName() {
		return this.nameName;
	}

	public void setNameName(String nameName) {
		this.nameName = nameName;
	}

	@Column(name = "NAME_RNAME", length = 20)
	public String getNameRname() {
		return this.nameRname;
	}

	public void setNameRname(String nameRname) {
		this.nameRname = nameRname;
	}

	@Column(name = "NAME_PNAME", length = 10)
	public String getNamePname() {
		return this.namePname;
	}

	public void setNamePname(String namePname) {
		this.namePname = namePname;
	}

	@Column(name = "NAME_TNAME", length = 4)
	public String getNameTname() {
		return this.nameTname;
	}

	public void setNameTname(String nameTname) {
		this.nameTname = nameTname;
	}

	@Column(name = "DEFAULT_TYPE", length = 1)
	public Character getDefaultType() {
		return this.defaultType;
	}

	public void setDefaultType(Character defaultType) {
		this.defaultType = defaultType;
	}

	@Column(name = "DSP_FLG", length = 1)
	public Character getDspFlg() {
		return this.dspFlg;
	}

	public void setDspFlg(Character dspFlg) {
		this.dspFlg = dspFlg;
	}

	@Column(name = "DSPORDER_NO", precision = 3, scale = 0)
	public Short getDsporderNo() {
		return this.dsporderNo;
	}

	public void setDsporderNo(Short dsporderNo) {
		this.dsporderNo = dsporderNo;
	}

	@Column(name = "NAMETYPE", length = 1)
	public Character getNametype() {
		return this.nametype;
	}

	public void setNametype(Character nametype) {
		this.nametype = nametype;
	}

	@Column(name = "ADD_USER", length = 10)
	public String getAddUser() {
		return this.addUser;
	}

	public void setAddUser(String addUser) {
		this.addUser = addUser;
	}

	@Column(name = "ADD_PC", length = 30)
	public String getAddPc() {
		return this.addPc;
	}

	public void setAddPc(String addPc) {
		this.addPc = addPc;
	}

	@Column(name = "ADD_DATE", precision = 8, scale = 0)
	public Integer getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Integer addDate) {
		this.addDate = addDate;
	}

	@Column(name = "ADD_TIME", precision = 6, scale = 0)
	public Integer getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Integer addTime) {
		this.addTime = addTime;
	}

	@Column(name = "LASTUP_USER", length = 10)
	public String getLastupUser() {
		return this.lastupUser;
	}

	public void setLastupUser(String lastupUser) {
		this.lastupUser = lastupUser;
	}

	@Column(name = "LASTUP_PC", length = 30)
	public String getLastupPc() {
		return this.lastupPc;
	}

	public void setLastupPc(String lastupPc) {
		this.lastupPc = lastupPc;
	}

	@Column(name = "LASTUP_DATE", precision = 8, scale = 0)
	public Integer getLastupDate() {
		return this.lastupDate;
	}

	public void setLastupDate(Integer lastupDate) {
		this.lastupDate = lastupDate;
	}

	@Column(name = "LASTUP_TIME", precision = 6, scale = 0)
	public Integer getLastupTime() {
		return this.lastupTime;
	}

	public void setLastupTime(Integer lastupTime) {
		this.lastupTime = lastupTime;
	}

}
