package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MOutctl generated by hbm2java
 */
@Entity
@Table(name = "M_OUTCTL", schema = "DB2ADMIN")
public class MOutctl implements java.io.Serializable {

	private String userid;
	private String out1Path;
	private String out2Path;
	private String out3Path;
	private String out4Path;
	private String out5Path;
	private String addUser;
	private String addPc;
	private Integer addDate;
	private Integer addTime;
	private String lastupUser;
	private String lastupPc;
	private Integer lastupDate;
	private Integer lastupTime;

	public MOutctl() {
	}

	public MOutctl(String userid) {
		this.userid = userid;
	}

	public MOutctl(String userid, String out1Path, String out2Path,
			String out3Path, String out4Path, String out5Path, String addUser,
			String addPc, Integer addDate, Integer addTime, String lastupUser,
			String lastupPc, Integer lastupDate, Integer lastupTime) {
		this.userid = userid;
		this.out1Path = out1Path;
		this.out2Path = out2Path;
		this.out3Path = out3Path;
		this.out4Path = out4Path;
		this.out5Path = out5Path;
		this.addUser = addUser;
		this.addPc = addPc;
		this.addDate = addDate;
		this.addTime = addTime;
		this.lastupUser = lastupUser;
		this.lastupPc = lastupPc;
		this.lastupDate = lastupDate;
		this.lastupTime = lastupTime;
	}

	@Id
	@Column(name = "USERID", unique = true, nullable = false, length = 10)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "OUT1_PATH", length = 200)
	public String getOut1Path() {
		return this.out1Path;
	}

	public void setOut1Path(String out1Path) {
		this.out1Path = out1Path;
	}

	@Column(name = "OUT2_PATH", length = 200)
	public String getOut2Path() {
		return this.out2Path;
	}

	public void setOut2Path(String out2Path) {
		this.out2Path = out2Path;
	}

	@Column(name = "OUT3_PATH", length = 200)
	public String getOut3Path() {
		return this.out3Path;
	}

	public void setOut3Path(String out3Path) {
		this.out3Path = out3Path;
	}

	@Column(name = "OUT4_PATH", length = 200)
	public String getOut4Path() {
		return this.out4Path;
	}

	public void setOut4Path(String out4Path) {
		this.out4Path = out4Path;
	}

	@Column(name = "OUT5_PATH", length = 200)
	public String getOut5Path() {
		return this.out5Path;
	}

	public void setOut5Path(String out5Path) {
		this.out5Path = out5Path;
	}

	@Column(name = "ADD_USER", length = 10)
	public String getAddUser() {
		return this.addUser;
	}

	public void setAddUser(String addUser) {
		this.addUser = addUser;
	}

	@Column(name = "ADD_PC", length = 30)
	public String getAddPc() {
		return this.addPc;
	}

	public void setAddPc(String addPc) {
		this.addPc = addPc;
	}

	@Column(name = "ADD_DATE", precision = 8, scale = 0)
	public Integer getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Integer addDate) {
		this.addDate = addDate;
	}

	@Column(name = "ADD_TIME", precision = 6, scale = 0)
	public Integer getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Integer addTime) {
		this.addTime = addTime;
	}

	@Column(name = "LASTUP_USER", length = 10)
	public String getLastupUser() {
		return this.lastupUser;
	}

	public void setLastupUser(String lastupUser) {
		this.lastupUser = lastupUser;
	}

	@Column(name = "LASTUP_PC", length = 30)
	public String getLastupPc() {
		return this.lastupPc;
	}

	public void setLastupPc(String lastupPc) {
		this.lastupPc = lastupPc;
	}

	@Column(name = "LASTUP_DATE", precision = 8, scale = 0)
	public Integer getLastupDate() {
		return this.lastupDate;
	}

	public void setLastupDate(Integer lastupDate) {
		this.lastupDate = lastupDate;
	}

	@Column(name = "LASTUP_TIME", precision = 6, scale = 0)
	public Integer getLastupTime() {
		return this.lastupTime;
	}

	public void setLastupTime(Integer lastupTime) {
		this.lastupTime = lastupTime;
	}

}
