package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MPost generated by hbm2java
 */
@Entity
@Table(name = "M_POST", schema = "DB2ADMIN")
public class MPost implements java.io.Serializable {

	private MPostId id;

	public MPost() {
	}

	public MPost(MPostId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "f1", column = @Column(name = "F1", nullable = false, length = 10)),
			@AttributeOverride(name = "f2", column = @Column(name = "F2", nullable = false, length = 10)),
			@AttributeOverride(name = "f3", column = @Column(name = "F3", nullable = false, length = 10)),
			@AttributeOverride(name = "f4", column = @Column(name = "F4", length = 50)),
			@AttributeOverride(name = "f5", column = @Column(name = "F5", length = 50)),
			@AttributeOverride(name = "f6", column = @Column(name = "F6", length = 50)),
			@AttributeOverride(name = "f7", column = @Column(name = "F7", length = 50)),
			@AttributeOverride(name = "f8", column = @Column(name = "F8", length = 50)),
			@AttributeOverride(name = "f9", column = @Column(name = "F9", length = 50)),
			@AttributeOverride(name = "f10", column = @Column(name = "F10", length = 1)),
			@AttributeOverride(name = "f11", column = @Column(name = "F11", length = 1)),
			@AttributeOverride(name = "f12", column = @Column(name = "F12", length = 1)),
			@AttributeOverride(name = "f13", column = @Column(name = "F13", length = 1)),
			@AttributeOverride(name = "f14", column = @Column(name = "F14", length = 1)),
			@AttributeOverride(name = "f15", column = @Column(name = "F15", length = 1)) })
	public MPostId getId() {
		return this.id;
	}

	public void setId(MPostId id) {
		this.id = id;
	}

}
