package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MPostId generated by hbm2java
 */
@Embeddable
public class MPostId implements java.io.Serializable {

	private String f1;
	private String f2;
	private String f3;
	private String f4;
	private String f5;
	private String f6;
	private String f7;
	private String f8;
	private String f9;
	private Character f10;
	private Character f11;
	private Character f12;
	private Character f13;
	private Character f14;
	private Character f15;

	public MPostId() {
	}

	public MPostId(String f1, String f2, String f3) {
		this.f1 = f1;
		this.f2 = f2;
		this.f3 = f3;
	}

	public MPostId(String f1, String f2, String f3, String f4, String f5,
			String f6, String f7, String f8, String f9, Character f10,
			Character f11, Character f12, Character f13, Character f14,
			Character f15) {
		this.f1 = f1;
		this.f2 = f2;
		this.f3 = f3;
		this.f4 = f4;
		this.f5 = f5;
		this.f6 = f6;
		this.f7 = f7;
		this.f8 = f8;
		this.f9 = f9;
		this.f10 = f10;
		this.f11 = f11;
		this.f12 = f12;
		this.f13 = f13;
		this.f14 = f14;
		this.f15 = f15;
	}

	@Column(name = "F1", nullable = false, length = 10)
	public String getF1() {
		return this.f1;
	}

	public void setF1(String f1) {
		this.f1 = f1;
	}

	@Column(name = "F2", nullable = false, length = 10)
	public String getF2() {
		return this.f2;
	}

	public void setF2(String f2) {
		this.f2 = f2;
	}

	@Column(name = "F3", nullable = false, length = 10)
	public String getF3() {
		return this.f3;
	}

	public void setF3(String f3) {
		this.f3 = f3;
	}

	@Column(name = "F4", length = 50)
	public String getF4() {
		return this.f4;
	}

	public void setF4(String f4) {
		this.f4 = f4;
	}

	@Column(name = "F5", length = 50)
	public String getF5() {
		return this.f5;
	}

	public void setF5(String f5) {
		this.f5 = f5;
	}

	@Column(name = "F6", length = 50)
	public String getF6() {
		return this.f6;
	}

	public void setF6(String f6) {
		this.f6 = f6;
	}

	@Column(name = "F7", length = 50)
	public String getF7() {
		return this.f7;
	}

	public void setF7(String f7) {
		this.f7 = f7;
	}

	@Column(name = "F8", length = 50)
	public String getF8() {
		return this.f8;
	}

	public void setF8(String f8) {
		this.f8 = f8;
	}

	@Column(name = "F9", length = 50)
	public String getF9() {
		return this.f9;
	}

	public void setF9(String f9) {
		this.f9 = f9;
	}

	@Column(name = "F10", length = 1)
	public Character getF10() {
		return this.f10;
	}

	public void setF10(Character f10) {
		this.f10 = f10;
	}

	@Column(name = "F11", length = 1)
	public Character getF11() {
		return this.f11;
	}

	public void setF11(Character f11) {
		this.f11 = f11;
	}

	@Column(name = "F12", length = 1)
	public Character getF12() {
		return this.f12;
	}

	public void setF12(Character f12) {
		this.f12 = f12;
	}

	@Column(name = "F13", length = 1)
	public Character getF13() {
		return this.f13;
	}

	public void setF13(Character f13) {
		this.f13 = f13;
	}

	@Column(name = "F14", length = 1)
	public Character getF14() {
		return this.f14;
	}

	public void setF14(Character f14) {
		this.f14 = f14;
	}

	@Column(name = "F15", length = 1)
	public Character getF15() {
		return this.f15;
	}

	public void setF15(Character f15) {
		this.f15 = f15;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MPostId))
			return false;
		MPostId castOther = (MPostId) other;

		return ((this.getF1() == castOther.getF1()) || (this.getF1() != null
				&& castOther.getF1() != null && this.getF1().equals(
				castOther.getF1())))
				&& ((this.getF2() == castOther.getF2()) || (this.getF2() != null
						&& castOther.getF2() != null && this.getF2().equals(
						castOther.getF2())))
				&& ((this.getF3() == castOther.getF3()) || (this.getF3() != null
						&& castOther.getF3() != null && this.getF3().equals(
						castOther.getF3())))
				&& ((this.getF4() == castOther.getF4()) || (this.getF4() != null
						&& castOther.getF4() != null && this.getF4().equals(
						castOther.getF4())))
				&& ((this.getF5() == castOther.getF5()) || (this.getF5() != null
						&& castOther.getF5() != null && this.getF5().equals(
						castOther.getF5())))
				&& ((this.getF6() == castOther.getF6()) || (this.getF6() != null
						&& castOther.getF6() != null && this.getF6().equals(
						castOther.getF6())))
				&& ((this.getF7() == castOther.getF7()) || (this.getF7() != null
						&& castOther.getF7() != null && this.getF7().equals(
						castOther.getF7())))
				&& ((this.getF8() == castOther.getF8()) || (this.getF8() != null
						&& castOther.getF8() != null && this.getF8().equals(
						castOther.getF8())))
				&& ((this.getF9() == castOther.getF9()) || (this.getF9() != null
						&& castOther.getF9() != null && this.getF9().equals(
						castOther.getF9())))
				&& ((this.getF10() == castOther.getF10()) || (this.getF10() != null
						&& castOther.getF10() != null && this.getF10().equals(
						castOther.getF10())))
				&& ((this.getF11() == castOther.getF11()) || (this.getF11() != null
						&& castOther.getF11() != null && this.getF11().equals(
						castOther.getF11())))
				&& ((this.getF12() == castOther.getF12()) || (this.getF12() != null
						&& castOther.getF12() != null && this.getF12().equals(
						castOther.getF12())))
				&& ((this.getF13() == castOther.getF13()) || (this.getF13() != null
						&& castOther.getF13() != null && this.getF13().equals(
						castOther.getF13())))
				&& ((this.getF14() == castOther.getF14()) || (this.getF14() != null
						&& castOther.getF14() != null && this.getF14().equals(
						castOther.getF14())))
				&& ((this.getF15() == castOther.getF15()) || (this.getF15() != null
						&& castOther.getF15() != null && this.getF15().equals(
						castOther.getF15())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getF1() == null ? 0 : this.getF1().hashCode());
		result = 37 * result + (getF2() == null ? 0 : this.getF2().hashCode());
		result = 37 * result + (getF3() == null ? 0 : this.getF3().hashCode());
		result = 37 * result + (getF4() == null ? 0 : this.getF4().hashCode());
		result = 37 * result + (getF5() == null ? 0 : this.getF5().hashCode());
		result = 37 * result + (getF6() == null ? 0 : this.getF6().hashCode());
		result = 37 * result + (getF7() == null ? 0 : this.getF7().hashCode());
		result = 37 * result + (getF8() == null ? 0 : this.getF8().hashCode());
		result = 37 * result + (getF9() == null ? 0 : this.getF9().hashCode());
		result = 37 * result
				+ (getF10() == null ? 0 : this.getF10().hashCode());
		result = 37 * result
				+ (getF11() == null ? 0 : this.getF11().hashCode());
		result = 37 * result
				+ (getF12() == null ? 0 : this.getF12().hashCode());
		result = 37 * result
				+ (getF13() == null ? 0 : this.getF13().hashCode());
		result = 37 * result
				+ (getF14() == null ? 0 : this.getF14().hashCode());
		result = 37 * result
				+ (getF15() == null ? 0 : this.getF15().hashCode());
		return result;
	}

}
