package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MSchdsp generated by hbm2java
 */
@Entity
@Table(name = "M_SCHDSP", schema = "DB2ADMIN")
public class MSchdsp implements java.io.Serializable {

	private String dspCode;
	private String dspName;
	private String schCtl;
	private String tblName;
	private String sqlId;
	private String ttlName1;
	private String ttlName2;
	private Character kbnGrp;
	private Character cmbItem1;
	private Character txtItem1;
	private Character spdCol1;
	private Character spdCol2;
	private Character spdCol3;
	private Character spdCol4;
	private Character spdCol5;
	private String spdColnm1;
	private String spdColnm2;
	private String spdColnm3;
	private String spdColnm4;
	private String spdColnm5;
	private Short spdColwd1;
	private Short spdColwd2;
	private Short spdColwd3;
	private Short spdColwd4;
	private Short spdColwd5;
	private Boolean spdColuse;
	private Boolean spdColwdc;
	private Boolean spdColhid;
	private Character schItem1;
	private Character schItem2;
	private Character schItem3;
	private Character schItem4;
	private Character schItem5;
	private Character schItem6;
	private String schName1;
	private String schName2;
	private String schName3;
	private String schName4;
	private String schName5;
	private String schName6;
	private Character chkUse;
	private Character kanaItem;
	private String helpHtml;
	private Character useFlg;
	private String addUser;
	private String addPc;
	private Integer addDate;
	private Integer addTime;
	private String lastupUser;
	private String lastupPc;
	private Integer lastupDate;
	private Integer lastupTime;

	public MSchdsp() {
	}

	public MSchdsp(String dspCode) {
		this.dspCode = dspCode;
	}

	public MSchdsp(String dspCode, String dspName, String schCtl,
			String tblName, String sqlId, String ttlName1, String ttlName2,
			Character kbnGrp, Character cmbItem1, Character txtItem1,
			Character spdCol1, Character spdCol2, Character spdCol3,
			Character spdCol4, Character spdCol5, String spdColnm1,
			String spdColnm2, String spdColnm3, String spdColnm4,
			String spdColnm5, Short spdColwd1, Short spdColwd2,
			Short spdColwd3, Short spdColwd4, Short spdColwd5,
			Boolean spdColuse, Boolean spdColwdc, Boolean spdColhid,
			Character schItem1, Character schItem2, Character schItem3,
			Character schItem4, Character schItem5, Character schItem6,
			String schName1, String schName2, String schName3, String schName4,
			String schName5, String schName6, Character chkUse,
			Character kanaItem, String helpHtml, Character useFlg,
			String addUser, String addPc, Integer addDate, Integer addTime,
			String lastupUser, String lastupPc, Integer lastupDate,
			Integer lastupTime) {
		this.dspCode = dspCode;
		this.dspName = dspName;
		this.schCtl = schCtl;
		this.tblName = tblName;
		this.sqlId = sqlId;
		this.ttlName1 = ttlName1;
		this.ttlName2 = ttlName2;
		this.kbnGrp = kbnGrp;
		this.cmbItem1 = cmbItem1;
		this.txtItem1 = txtItem1;
		this.spdCol1 = spdCol1;
		this.spdCol2 = spdCol2;
		this.spdCol3 = spdCol3;
		this.spdCol4 = spdCol4;
		this.spdCol5 = spdCol5;
		this.spdColnm1 = spdColnm1;
		this.spdColnm2 = spdColnm2;
		this.spdColnm3 = spdColnm3;
		this.spdColnm4 = spdColnm4;
		this.spdColnm5 = spdColnm5;
		this.spdColwd1 = spdColwd1;
		this.spdColwd2 = spdColwd2;
		this.spdColwd3 = spdColwd3;
		this.spdColwd4 = spdColwd4;
		this.spdColwd5 = spdColwd5;
		this.spdColuse = spdColuse;
		this.spdColwdc = spdColwdc;
		this.spdColhid = spdColhid;
		this.schItem1 = schItem1;
		this.schItem2 = schItem2;
		this.schItem3 = schItem3;
		this.schItem4 = schItem4;
		this.schItem5 = schItem5;
		this.schItem6 = schItem6;
		this.schName1 = schName1;
		this.schName2 = schName2;
		this.schName3 = schName3;
		this.schName4 = schName4;
		this.schName5 = schName5;
		this.schName6 = schName6;
		this.chkUse = chkUse;
		this.kanaItem = kanaItem;
		this.helpHtml = helpHtml;
		this.useFlg = useFlg;
		this.addUser = addUser;
		this.addPc = addPc;
		this.addDate = addDate;
		this.addTime = addTime;
		this.lastupUser = lastupUser;
		this.lastupPc = lastupPc;
		this.lastupDate = lastupDate;
		this.lastupTime = lastupTime;
	}

	@Id
	@Column(name = "DSP_CODE", unique = true, nullable = false, length = 6)
	public String getDspCode() {
		return this.dspCode;
	}

	public void setDspCode(String dspCode) {
		this.dspCode = dspCode;
	}

	@Column(name = "DSP_NAME", length = 24)
	public String getDspName() {
		return this.dspName;
	}

	public void setDspName(String dspName) {
		this.dspName = dspName;
	}

	@Column(name = "SCH_CTL", length = 12)
	public String getSchCtl() {
		return this.schCtl;
	}

	public void setSchCtl(String schCtl) {
		this.schCtl = schCtl;
	}

	@Column(name = "TBL_NAME", length = 20)
	public String getTblName() {
		return this.tblName;
	}

	public void setTblName(String tblName) {
		this.tblName = tblName;
	}

	@Column(name = "SQL_ID", length = 20)
	public String getSqlId() {
		return this.sqlId;
	}

	public void setSqlId(String sqlId) {
		this.sqlId = sqlId;
	}

	@Column(name = "TTL_NAME1", length = 12)
	public String getTtlName1() {
		return this.ttlName1;
	}

	public void setTtlName1(String ttlName1) {
		this.ttlName1 = ttlName1;
	}

	@Column(name = "TTL_NAME2", length = 12)
	public String getTtlName2() {
		return this.ttlName2;
	}

	public void setTtlName2(String ttlName2) {
		this.ttlName2 = ttlName2;
	}

	@Column(name = "KBN_GRP", length = 1)
	public Character getKbnGrp() {
		return this.kbnGrp;
	}

	public void setKbnGrp(Character kbnGrp) {
		this.kbnGrp = kbnGrp;
	}

	@Column(name = "CMB_ITEM1", length = 1)
	public Character getCmbItem1() {
		return this.cmbItem1;
	}

	public void setCmbItem1(Character cmbItem1) {
		this.cmbItem1 = cmbItem1;
	}

	@Column(name = "TXT_ITEM1", length = 1)
	public Character getTxtItem1() {
		return this.txtItem1;
	}

	public void setTxtItem1(Character txtItem1) {
		this.txtItem1 = txtItem1;
	}

	@Column(name = "SPD_COL1", length = 1)
	public Character getSpdCol1() {
		return this.spdCol1;
	}

	public void setSpdCol1(Character spdCol1) {
		this.spdCol1 = spdCol1;
	}

	@Column(name = "SPD_COL2", length = 1)
	public Character getSpdCol2() {
		return this.spdCol2;
	}

	public void setSpdCol2(Character spdCol2) {
		this.spdCol2 = spdCol2;
	}

	@Column(name = "SPD_COL3", length = 1)
	public Character getSpdCol3() {
		return this.spdCol3;
	}

	public void setSpdCol3(Character spdCol3) {
		this.spdCol3 = spdCol3;
	}

	@Column(name = "SPD_COL4", length = 1)
	public Character getSpdCol4() {
		return this.spdCol4;
	}

	public void setSpdCol4(Character spdCol4) {
		this.spdCol4 = spdCol4;
	}

	@Column(name = "SPD_COL5", length = 1)
	public Character getSpdCol5() {
		return this.spdCol5;
	}

	public void setSpdCol5(Character spdCol5) {
		this.spdCol5 = spdCol5;
	}

	@Column(name = "SPD_COLNM1", length = 22)
	public String getSpdColnm1() {
		return this.spdColnm1;
	}

	public void setSpdColnm1(String spdColnm1) {
		this.spdColnm1 = spdColnm1;
	}

	@Column(name = "SPD_COLNM2", length = 22)
	public String getSpdColnm2() {
		return this.spdColnm2;
	}

	public void setSpdColnm2(String spdColnm2) {
		this.spdColnm2 = spdColnm2;
	}

	@Column(name = "SPD_COLNM3", length = 22)
	public String getSpdColnm3() {
		return this.spdColnm3;
	}

	public void setSpdColnm3(String spdColnm3) {
		this.spdColnm3 = spdColnm3;
	}

	@Column(name = "SPD_COLNM4", length = 22)
	public String getSpdColnm4() {
		return this.spdColnm4;
	}

	public void setSpdColnm4(String spdColnm4) {
		this.spdColnm4 = spdColnm4;
	}

	@Column(name = "SPD_COLNM5", length = 22)
	public String getSpdColnm5() {
		return this.spdColnm5;
	}

	public void setSpdColnm5(String spdColnm5) {
		this.spdColnm5 = spdColnm5;
	}

	@Column(name = "SPD_COLWD1", precision = 3, scale = 0)
	public Short getSpdColwd1() {
		return this.spdColwd1;
	}

	public void setSpdColwd1(Short spdColwd1) {
		this.spdColwd1 = spdColwd1;
	}

	@Column(name = "SPD_COLWD2", precision = 3, scale = 0)
	public Short getSpdColwd2() {
		return this.spdColwd2;
	}

	public void setSpdColwd2(Short spdColwd2) {
		this.spdColwd2 = spdColwd2;
	}

	@Column(name = "SPD_COLWD3", precision = 3, scale = 0)
	public Short getSpdColwd3() {
		return this.spdColwd3;
	}

	public void setSpdColwd3(Short spdColwd3) {
		this.spdColwd3 = spdColwd3;
	}

	@Column(name = "SPD_COLWD4", precision = 3, scale = 0)
	public Short getSpdColwd4() {
		return this.spdColwd4;
	}

	public void setSpdColwd4(Short spdColwd4) {
		this.spdColwd4 = spdColwd4;
	}

	@Column(name = "SPD_COLWD5", precision = 3, scale = 0)
	public Short getSpdColwd5() {
		return this.spdColwd5;
	}

	public void setSpdColwd5(Short spdColwd5) {
		this.spdColwd5 = spdColwd5;
	}

	@Column(name = "SPD_COLUSE", precision = 1, scale = 0)
	public Boolean getSpdColuse() {
		return this.spdColuse;
	}

	public void setSpdColuse(Boolean spdColuse) {
		this.spdColuse = spdColuse;
	}

	@Column(name = "SPD_COLWDC", precision = 1, scale = 0)
	public Boolean getSpdColwdc() {
		return this.spdColwdc;
	}

	public void setSpdColwdc(Boolean spdColwdc) {
		this.spdColwdc = spdColwdc;
	}

	@Column(name = "SPD_COLHID", precision = 1, scale = 0)
	public Boolean getSpdColhid() {
		return this.spdColhid;
	}

	public void setSpdColhid(Boolean spdColhid) {
		this.spdColhid = spdColhid;
	}

	@Column(name = "SCH_ITEM1", length = 1)
	public Character getSchItem1() {
		return this.schItem1;
	}

	public void setSchItem1(Character schItem1) {
		this.schItem1 = schItem1;
	}

	@Column(name = "SCH_ITEM2", length = 1)
	public Character getSchItem2() {
		return this.schItem2;
	}

	public void setSchItem2(Character schItem2) {
		this.schItem2 = schItem2;
	}

	@Column(name = "SCH_ITEM3", length = 1)
	public Character getSchItem3() {
		return this.schItem3;
	}

	public void setSchItem3(Character schItem3) {
		this.schItem3 = schItem3;
	}

	@Column(name = "SCH_ITEM4", length = 1)
	public Character getSchItem4() {
		return this.schItem4;
	}

	public void setSchItem4(Character schItem4) {
		this.schItem4 = schItem4;
	}

	@Column(name = "SCH_ITEM5", length = 1)
	public Character getSchItem5() {
		return this.schItem5;
	}

	public void setSchItem5(Character schItem5) {
		this.schItem5 = schItem5;
	}

	@Column(name = "SCH_ITEM6", length = 1)
	public Character getSchItem6() {
		return this.schItem6;
	}

	public void setSchItem6(Character schItem6) {
		this.schItem6 = schItem6;
	}

	@Column(name = "SCH_NAME1", length = 10)
	public String getSchName1() {
		return this.schName1;
	}

	public void setSchName1(String schName1) {
		this.schName1 = schName1;
	}

	@Column(name = "SCH_NAME2", length = 10)
	public String getSchName2() {
		return this.schName2;
	}

	public void setSchName2(String schName2) {
		this.schName2 = schName2;
	}

	@Column(name = "SCH_NAME3", length = 10)
	public String getSchName3() {
		return this.schName3;
	}

	public void setSchName3(String schName3) {
		this.schName3 = schName3;
	}

	@Column(name = "SCH_NAME4", length = 10)
	public String getSchName4() {
		return this.schName4;
	}

	public void setSchName4(String schName4) {
		this.schName4 = schName4;
	}

	@Column(name = "SCH_NAME5", length = 10)
	public String getSchName5() {
		return this.schName5;
	}

	public void setSchName5(String schName5) {
		this.schName5 = schName5;
	}

	@Column(name = "SCH_NAME6", length = 10)
	public String getSchName6() {
		return this.schName6;
	}

	public void setSchName6(String schName6) {
		this.schName6 = schName6;
	}

	@Column(name = "CHK_USE", length = 1)
	public Character getChkUse() {
		return this.chkUse;
	}

	public void setChkUse(Character chkUse) {
		this.chkUse = chkUse;
	}

	@Column(name = "KANA_ITEM", length = 1)
	public Character getKanaItem() {
		return this.kanaItem;
	}

	public void setKanaItem(Character kanaItem) {
		this.kanaItem = kanaItem;
	}

	@Column(name = "HELP_HTML", length = 30)
	public String getHelpHtml() {
		return this.helpHtml;
	}

	public void setHelpHtml(String helpHtml) {
		this.helpHtml = helpHtml;
	}

	@Column(name = "USE_FLG", length = 1)
	public Character getUseFlg() {
		return this.useFlg;
	}

	public void setUseFlg(Character useFlg) {
		this.useFlg = useFlg;
	}

	@Column(name = "ADD_USER", length = 10)
	public String getAddUser() {
		return this.addUser;
	}

	public void setAddUser(String addUser) {
		this.addUser = addUser;
	}

	@Column(name = "ADD_PC", length = 30)
	public String getAddPc() {
		return this.addPc;
	}

	public void setAddPc(String addPc) {
		this.addPc = addPc;
	}

	@Column(name = "ADD_DATE", precision = 8, scale = 0)
	public Integer getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Integer addDate) {
		this.addDate = addDate;
	}

	@Column(name = "ADD_TIME", precision = 6, scale = 0)
	public Integer getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Integer addTime) {
		this.addTime = addTime;
	}

	@Column(name = "LASTUP_USER", length = 10)
	public String getLastupUser() {
		return this.lastupUser;
	}

	public void setLastupUser(String lastupUser) {
		this.lastupUser = lastupUser;
	}

	@Column(name = "LASTUP_PC", length = 30)
	public String getLastupPc() {
		return this.lastupPc;
	}

	public void setLastupPc(String lastupPc) {
		this.lastupPc = lastupPc;
	}

	@Column(name = "LASTUP_DATE", precision = 8, scale = 0)
	public Integer getLastupDate() {
		return this.lastupDate;
	}

	public void setLastupDate(Integer lastupDate) {
		this.lastupDate = lastupDate;
	}

	@Column(name = "LASTUP_TIME", precision = 6, scale = 0)
	public Integer getLastupTime() {
		return this.lastupTime;
	}

	public void setLastupTime(Integer lastupTime) {
		this.lastupTime = lastupTime;
	}

}
