package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MUsergrp generated by hbm2java
 */
@Entity
@Table(name = "M_USERGRP", schema = "DB2ADMIN")
public class MUsergrp implements java.io.Serializable {

	private String usergid;
	private String pwd;
	private String usertxt;
	private Character logviewFlg;
	private Character excelout;
	private Integer pwdDate;
	private String pwd1;
	private String pwd2;
	private String pwd3;
	private String addUser;
	private String addPc;
	private Integer addDate;
	private Integer addTime;
	private String lastupUser;
	private String lastupPc;
	private Integer lastupDate;
	private Integer lastupTime;

	public MUsergrp() {
	}

	public MUsergrp(String usergid) {
		this.usergid = usergid;
	}

	public MUsergrp(String usergid, String pwd, String usertxt,
			Character logviewFlg, Character excelout, Integer pwdDate,
			String pwd1, String pwd2, String pwd3, String addUser,
			String addPc, Integer addDate, Integer addTime, String lastupUser,
			String lastupPc, Integer lastupDate, Integer lastupTime) {
		this.usergid = usergid;
		this.pwd = pwd;
		this.usertxt = usertxt;
		this.logviewFlg = logviewFlg;
		this.excelout = excelout;
		this.pwdDate = pwdDate;
		this.pwd1 = pwd1;
		this.pwd2 = pwd2;
		this.pwd3 = pwd3;
		this.addUser = addUser;
		this.addPc = addPc;
		this.addDate = addDate;
		this.addTime = addTime;
		this.lastupUser = lastupUser;
		this.lastupPc = lastupPc;
		this.lastupDate = lastupDate;
		this.lastupTime = lastupTime;
	}

	@Id
	@Column(name = "USERGID", unique = true, nullable = false, length = 10)
	public String getUsergid() {
		return this.usergid;
	}

	public void setUsergid(String usergid) {
		this.usergid = usergid;
	}

	@Column(name = "PWD", length = 16)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "USERTXT", length = 24)
	public String getUsertxt() {
		return this.usertxt;
	}

	public void setUsertxt(String usertxt) {
		this.usertxt = usertxt;
	}

	@Column(name = "LOGVIEW_FLG", length = 1)
	public Character getLogviewFlg() {
		return this.logviewFlg;
	}

	public void setLogviewFlg(Character logviewFlg) {
		this.logviewFlg = logviewFlg;
	}

	@Column(name = "EXCELOUT", length = 1)
	public Character getExcelout() {
		return this.excelout;
	}

	public void setExcelout(Character excelout) {
		this.excelout = excelout;
	}

	@Column(name = "PWD_DATE", precision = 8, scale = 0)
	public Integer getPwdDate() {
		return this.pwdDate;
	}

	public void setPwdDate(Integer pwdDate) {
		this.pwdDate = pwdDate;
	}

	@Column(name = "PWD1", length = 16)
	public String getPwd1() {
		return this.pwd1;
	}

	public void setPwd1(String pwd1) {
		this.pwd1 = pwd1;
	}

	@Column(name = "PWD2", length = 16)
	public String getPwd2() {
		return this.pwd2;
	}

	public void setPwd2(String pwd2) {
		this.pwd2 = pwd2;
	}

	@Column(name = "PWD3", length = 16)
	public String getPwd3() {
		return this.pwd3;
	}

	public void setPwd3(String pwd3) {
		this.pwd3 = pwd3;
	}

	@Column(name = "ADD_USER", length = 10)
	public String getAddUser() {
		return this.addUser;
	}

	public void setAddUser(String addUser) {
		this.addUser = addUser;
	}

	@Column(name = "ADD_PC", length = 30)
	public String getAddPc() {
		return this.addPc;
	}

	public void setAddPc(String addPc) {
		this.addPc = addPc;
	}

	@Column(name = "ADD_DATE", precision = 8, scale = 0)
	public Integer getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Integer addDate) {
		this.addDate = addDate;
	}

	@Column(name = "ADD_TIME", precision = 6, scale = 0)
	public Integer getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Integer addTime) {
		this.addTime = addTime;
	}

	@Column(name = "LASTUP_USER", length = 10)
	public String getLastupUser() {
		return this.lastupUser;
	}

	public void setLastupUser(String lastupUser) {
		this.lastupUser = lastupUser;
	}

	@Column(name = "LASTUP_PC", length = 30)
	public String getLastupPc() {
		return this.lastupPc;
	}

	public void setLastupPc(String lastupPc) {
		this.lastupPc = lastupPc;
	}

	@Column(name = "LASTUP_DATE", precision = 8, scale = 0)
	public Integer getLastupDate() {
		return this.lastupDate;
	}

	public void setLastupDate(Integer lastupDate) {
		this.lastupDate = lastupDate;
	}

	@Column(name = "LASTUP_TIME", precision = 6, scale = 0)
	public Integer getLastupTime() {
		return this.lastupTime;
	}

	public void setLastupTime(Integer lastupTime) {
		this.lastupTime = lastupTime;
	}

}
