package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pc01 generated by hbm2java
 */
@Entity
@Table(name = "PC01", schema = "DB2ADMIN")
public class Pc01 implements java.io.Serializable {

	private short c0101;
	private Short c0102;
	private Boolean c0103;
	private String c0104;
	private Boolean c0105;
	private Integer c0106;
	private Integer c0107;
	private Integer c0108;
	private Integer c0109;
	private Integer c0110;
	private Byte c0111;
	private Byte c0112;
	private Byte c0113;
	private Byte c0114;
	private Byte c0115;
	private Byte c0116;
	private Byte c0117;
	private Byte c0118;
	private Byte c0119;
	private Integer c0120;
	private Boolean c0121;
	private String c0122;
	private String c0123;
	private String c0124;
	private String c0125;
	private Long c0126;
	private String c0127;
	private String c0128;
	private BigDecimal c0129;
	private BigDecimal c0130;
	private BigDecimal c0131;
	private BigDecimal c0132;
	private BigDecimal c0133;
	private BigDecimal c0134;
	private BigDecimal c0135;
	private BigDecimal c0136;
	private BigDecimal c0137;
	private BigDecimal c0138;
	private BigDecimal c0139;
	private BigDecimal c0140;
	private BigDecimal c0141;
	private BigDecimal c0142;
	private BigDecimal c0143;
	private BigDecimal c0144;
	private BigDecimal c0145;
	private BigDecimal c0146;
	private BigDecimal c0147;
	private BigDecimal c0148;
	private BigDecimal c0149;
	private BigDecimal c0150;
	private BigDecimal c0151;
	private BigDecimal c0152;
	private BigDecimal c0153;
	private BigDecimal c0154;
	private BigDecimal c0155;
	private BigDecimal c0156;
	private BigDecimal c0157;
	private BigDecimal c0158;
	private BigDecimal c0159;
	private BigDecimal c0160;
	private BigDecimal c0161;
	private BigDecimal c0162;
	private BigDecimal c0163;
	private BigDecimal c0164;
	private BigDecimal c0165;
	private BigDecimal c0166;
	private BigDecimal c0167;
	private Boolean c0168;
	private Short c0169;
	private Byte c0170;
	private Byte c0171;
	private Byte c0172;
	private Byte c0173;
	private Byte c0174;
	private Byte c0175;
	private Byte c0176;
	private Byte c0177;
	private Byte c0178;
	private Boolean c0179;
	private String c0180;
	private String c0181;
	private String c0182;
	private Long c0183;
	private String c0184;
	private String c0185;
	private Short c0186;
	private Short c0187;
	private Boolean c0188;
	private Boolean c0189;
	private String c0190;
	private String c0191;
	private String c01dm;

	public Pc01() {
	}

	public Pc01(short c0101) {
		this.c0101 = c0101;
	}

	public Pc01(short c0101, Short c0102, Boolean c0103, String c0104,
			Boolean c0105, Integer c0106, Integer c0107, Integer c0108,
			Integer c0109, Integer c0110, Byte c0111, Byte c0112, Byte c0113,
			Byte c0114, Byte c0115, Byte c0116, Byte c0117, Byte c0118,
			Byte c0119, Integer c0120, Boolean c0121, String c0122,
			String c0123, String c0124, String c0125, Long c0126, String c0127,
			String c0128, BigDecimal c0129, BigDecimal c0130, BigDecimal c0131,
			BigDecimal c0132, BigDecimal c0133, BigDecimal c0134,
			BigDecimal c0135, BigDecimal c0136, BigDecimal c0137,
			BigDecimal c0138, BigDecimal c0139, BigDecimal c0140,
			BigDecimal c0141, BigDecimal c0142, BigDecimal c0143,
			BigDecimal c0144, BigDecimal c0145, BigDecimal c0146,
			BigDecimal c0147, BigDecimal c0148, BigDecimal c0149,
			BigDecimal c0150, BigDecimal c0151, BigDecimal c0152,
			BigDecimal c0153, BigDecimal c0154, BigDecimal c0155,
			BigDecimal c0156, BigDecimal c0157, BigDecimal c0158,
			BigDecimal c0159, BigDecimal c0160, BigDecimal c0161,
			BigDecimal c0162, BigDecimal c0163, BigDecimal c0164,
			BigDecimal c0165, BigDecimal c0166, BigDecimal c0167,
			Boolean c0168, Short c0169, Byte c0170, Byte c0171, Byte c0172,
			Byte c0173, Byte c0174, Byte c0175, Byte c0176, Byte c0177,
			Byte c0178, Boolean c0179, String c0180, String c0181,
			String c0182, Long c0183, String c0184, String c0185, Short c0186,
			Short c0187, Boolean c0188, Boolean c0189, String c0190,
			String c0191, String c01dm) {
		this.c0101 = c0101;
		this.c0102 = c0102;
		this.c0103 = c0103;
		this.c0104 = c0104;
		this.c0105 = c0105;
		this.c0106 = c0106;
		this.c0107 = c0107;
		this.c0108 = c0108;
		this.c0109 = c0109;
		this.c0110 = c0110;
		this.c0111 = c0111;
		this.c0112 = c0112;
		this.c0113 = c0113;
		this.c0114 = c0114;
		this.c0115 = c0115;
		this.c0116 = c0116;
		this.c0117 = c0117;
		this.c0118 = c0118;
		this.c0119 = c0119;
		this.c0120 = c0120;
		this.c0121 = c0121;
		this.c0122 = c0122;
		this.c0123 = c0123;
		this.c0124 = c0124;
		this.c0125 = c0125;
		this.c0126 = c0126;
		this.c0127 = c0127;
		this.c0128 = c0128;
		this.c0129 = c0129;
		this.c0130 = c0130;
		this.c0131 = c0131;
		this.c0132 = c0132;
		this.c0133 = c0133;
		this.c0134 = c0134;
		this.c0135 = c0135;
		this.c0136 = c0136;
		this.c0137 = c0137;
		this.c0138 = c0138;
		this.c0139 = c0139;
		this.c0140 = c0140;
		this.c0141 = c0141;
		this.c0142 = c0142;
		this.c0143 = c0143;
		this.c0144 = c0144;
		this.c0145 = c0145;
		this.c0146 = c0146;
		this.c0147 = c0147;
		this.c0148 = c0148;
		this.c0149 = c0149;
		this.c0150 = c0150;
		this.c0151 = c0151;
		this.c0152 = c0152;
		this.c0153 = c0153;
		this.c0154 = c0154;
		this.c0155 = c0155;
		this.c0156 = c0156;
		this.c0157 = c0157;
		this.c0158 = c0158;
		this.c0159 = c0159;
		this.c0160 = c0160;
		this.c0161 = c0161;
		this.c0162 = c0162;
		this.c0163 = c0163;
		this.c0164 = c0164;
		this.c0165 = c0165;
		this.c0166 = c0166;
		this.c0167 = c0167;
		this.c0168 = c0168;
		this.c0169 = c0169;
		this.c0170 = c0170;
		this.c0171 = c0171;
		this.c0172 = c0172;
		this.c0173 = c0173;
		this.c0174 = c0174;
		this.c0175 = c0175;
		this.c0176 = c0176;
		this.c0177 = c0177;
		this.c0178 = c0178;
		this.c0179 = c0179;
		this.c0180 = c0180;
		this.c0181 = c0181;
		this.c0182 = c0182;
		this.c0183 = c0183;
		this.c0184 = c0184;
		this.c0185 = c0185;
		this.c0186 = c0186;
		this.c0187 = c0187;
		this.c0188 = c0188;
		this.c0189 = c0189;
		this.c0190 = c0190;
		this.c0191 = c0191;
		this.c01dm = c01dm;
	}

	@Id
	@Column(name = "C0101", unique = true, nullable = false, precision = 4, scale = 0)
	public short getC0101() {
		return this.c0101;
	}

	public void setC0101(short c0101) {
		this.c0101 = c0101;
	}

	@Column(name = "C0102", precision = 4, scale = 0)
	public Short getC0102() {
		return this.c0102;
	}

	public void setC0102(Short c0102) {
		this.c0102 = c0102;
	}

	@Column(name = "C0103", precision = 1, scale = 0)
	public Boolean getC0103() {
		return this.c0103;
	}

	public void setC0103(Boolean c0103) {
		this.c0103 = c0103;
	}

	@Column(name = "C0104", length = 2)
	public String getC0104() {
		return this.c0104;
	}

	public void setC0104(String c0104) {
		this.c0104 = c0104;
	}

	@Column(name = "C0105", precision = 1, scale = 0)
	public Boolean getC0105() {
		return this.c0105;
	}

	public void setC0105(Boolean c0105) {
		this.c0105 = c0105;
	}

	@Column(name = "C0106", precision = 7, scale = 0)
	public Integer getC0106() {
		return this.c0106;
	}

	public void setC0106(Integer c0106) {
		this.c0106 = c0106;
	}

	@Column(name = "C0107", precision = 7, scale = 0)
	public Integer getC0107() {
		return this.c0107;
	}

	public void setC0107(Integer c0107) {
		this.c0107 = c0107;
	}

	@Column(name = "C0108", precision = 7, scale = 0)
	public Integer getC0108() {
		return this.c0108;
	}

	public void setC0108(Integer c0108) {
		this.c0108 = c0108;
	}

	@Column(name = "C0109", precision = 7, scale = 0)
	public Integer getC0109() {
		return this.c0109;
	}

	public void setC0109(Integer c0109) {
		this.c0109 = c0109;
	}

	@Column(name = "C0110", precision = 7, scale = 0)
	public Integer getC0110() {
		return this.c0110;
	}

	public void setC0110(Integer c0110) {
		this.c0110 = c0110;
	}

	@Column(name = "C0111", precision = 2, scale = 0)
	public Byte getC0111() {
		return this.c0111;
	}

	public void setC0111(Byte c0111) {
		this.c0111 = c0111;
	}

	@Column(name = "C0112", precision = 2, scale = 0)
	public Byte getC0112() {
		return this.c0112;
	}

	public void setC0112(Byte c0112) {
		this.c0112 = c0112;
	}

	@Column(name = "C0113", precision = 2, scale = 0)
	public Byte getC0113() {
		return this.c0113;
	}

	public void setC0113(Byte c0113) {
		this.c0113 = c0113;
	}

	@Column(name = "C0114", precision = 2, scale = 0)
	public Byte getC0114() {
		return this.c0114;
	}

	public void setC0114(Byte c0114) {
		this.c0114 = c0114;
	}

	@Column(name = "C0115", precision = 2, scale = 0)
	public Byte getC0115() {
		return this.c0115;
	}

	public void setC0115(Byte c0115) {
		this.c0115 = c0115;
	}

	@Column(name = "C0116", precision = 2, scale = 0)
	public Byte getC0116() {
		return this.c0116;
	}

	public void setC0116(Byte c0116) {
		this.c0116 = c0116;
	}

	@Column(name = "C0117", precision = 2, scale = 0)
	public Byte getC0117() {
		return this.c0117;
	}

	public void setC0117(Byte c0117) {
		this.c0117 = c0117;
	}

	@Column(name = "C0118", precision = 2, scale = 0)
	public Byte getC0118() {
		return this.c0118;
	}

	public void setC0118(Byte c0118) {
		this.c0118 = c0118;
	}

	@Column(name = "C0119", precision = 2, scale = 0)
	public Byte getC0119() {
		return this.c0119;
	}

	public void setC0119(Byte c0119) {
		this.c0119 = c0119;
	}

	@Column(name = "C0120", precision = 7, scale = 0)
	public Integer getC0120() {
		return this.c0120;
	}

	public void setC0120(Integer c0120) {
		this.c0120 = c0120;
	}

	@Column(name = "C0121", precision = 1, scale = 0)
	public Boolean getC0121() {
		return this.c0121;
	}

	public void setC0121(Boolean c0121) {
		this.c0121 = c0121;
	}

	@Column(name = "C0122", length = 32)
	public String getC0122() {
		return this.c0122;
	}

	public void setC0122(String c0122) {
		this.c0122 = c0122;
	}

	@Column(name = "C0123", length = 32)
	public String getC0123() {
		return this.c0123;
	}

	public void setC0123(String c0123) {
		this.c0123 = c0123;
	}

	@Column(name = "C0124", length = 30)
	public String getC0124() {
		return this.c0124;
	}

	public void setC0124(String c0124) {
		this.c0124 = c0124;
	}

	@Column(name = "C0125", length = 8)
	public String getC0125() {
		return this.c0125;
	}

	public void setC0125(String c0125) {
		this.c0125 = c0125;
	}

	@Column(name = "C0126", precision = 12, scale = 0)
	public Long getC0126() {
		return this.c0126;
	}

	public void setC0126(Long c0126) {
		this.c0126 = c0126;
	}

	@Column(name = "C0127", length = 34)
	public String getC0127() {
		return this.c0127;
	}

	public void setC0127(String c0127) {
		this.c0127 = c0127;
	}

	@Column(name = "C0128", length = 12)
	public String getC0128() {
		return this.c0128;
	}

	public void setC0128(String c0128) {
		this.c0128 = c0128;
	}

	@Column(name = "C0129", precision = 7)
	public BigDecimal getC0129() {
		return this.c0129;
	}

	public void setC0129(BigDecimal c0129) {
		this.c0129 = c0129;
	}

	@Column(name = "C0130", precision = 4)
	public BigDecimal getC0130() {
		return this.c0130;
	}

	public void setC0130(BigDecimal c0130) {
		this.c0130 = c0130;
	}

	@Column(name = "C0131", precision = 4)
	public BigDecimal getC0131() {
		return this.c0131;
	}

	public void setC0131(BigDecimal c0131) {
		this.c0131 = c0131;
	}

	@Column(name = "C0132", precision = 4)
	public BigDecimal getC0132() {
		return this.c0132;
	}

	public void setC0132(BigDecimal c0132) {
		this.c0132 = c0132;
	}

	@Column(name = "C0133", precision = 4)
	public BigDecimal getC0133() {
		return this.c0133;
	}

	public void setC0133(BigDecimal c0133) {
		this.c0133 = c0133;
	}

	@Column(name = "C0134", precision = 4)
	public BigDecimal getC0134() {
		return this.c0134;
	}

	public void setC0134(BigDecimal c0134) {
		this.c0134 = c0134;
	}

	@Column(name = "C0135", precision = 4)
	public BigDecimal getC0135() {
		return this.c0135;
	}

	public void setC0135(BigDecimal c0135) {
		this.c0135 = c0135;
	}

	@Column(name = "C0136", precision = 4)
	public BigDecimal getC0136() {
		return this.c0136;
	}

	public void setC0136(BigDecimal c0136) {
		this.c0136 = c0136;
	}

	@Column(name = "C0137", precision = 4)
	public BigDecimal getC0137() {
		return this.c0137;
	}

	public void setC0137(BigDecimal c0137) {
		this.c0137 = c0137;
	}

	@Column(name = "C0138", precision = 4)
	public BigDecimal getC0138() {
		return this.c0138;
	}

	public void setC0138(BigDecimal c0138) {
		this.c0138 = c0138;
	}

	@Column(name = "C0139", precision = 4)
	public BigDecimal getC0139() {
		return this.c0139;
	}

	public void setC0139(BigDecimal c0139) {
		this.c0139 = c0139;
	}

	@Column(name = "C0140", precision = 4)
	public BigDecimal getC0140() {
		return this.c0140;
	}

	public void setC0140(BigDecimal c0140) {
		this.c0140 = c0140;
	}

	@Column(name = "C0141", precision = 4)
	public BigDecimal getC0141() {
		return this.c0141;
	}

	public void setC0141(BigDecimal c0141) {
		this.c0141 = c0141;
	}

	@Column(name = "C0142", precision = 4)
	public BigDecimal getC0142() {
		return this.c0142;
	}

	public void setC0142(BigDecimal c0142) {
		this.c0142 = c0142;
	}

	@Column(name = "C0143", precision = 4)
	public BigDecimal getC0143() {
		return this.c0143;
	}

	public void setC0143(BigDecimal c0143) {
		this.c0143 = c0143;
	}

	@Column(name = "C0144", precision = 4)
	public BigDecimal getC0144() {
		return this.c0144;
	}

	public void setC0144(BigDecimal c0144) {
		this.c0144 = c0144;
	}

	@Column(name = "C0145", precision = 4)
	public BigDecimal getC0145() {
		return this.c0145;
	}

	public void setC0145(BigDecimal c0145) {
		this.c0145 = c0145;
	}

	@Column(name = "C0146", precision = 4)
	public BigDecimal getC0146() {
		return this.c0146;
	}

	public void setC0146(BigDecimal c0146) {
		this.c0146 = c0146;
	}

	@Column(name = "C0147", precision = 7)
	public BigDecimal getC0147() {
		return this.c0147;
	}

	public void setC0147(BigDecimal c0147) {
		this.c0147 = c0147;
	}

	@Column(name = "C0148", precision = 4)
	public BigDecimal getC0148() {
		return this.c0148;
	}

	public void setC0148(BigDecimal c0148) {
		this.c0148 = c0148;
	}

	@Column(name = "C0149", precision = 4)
	public BigDecimal getC0149() {
		return this.c0149;
	}

	public void setC0149(BigDecimal c0149) {
		this.c0149 = c0149;
	}

	@Column(name = "C0150", precision = 4)
	public BigDecimal getC0150() {
		return this.c0150;
	}

	public void setC0150(BigDecimal c0150) {
		this.c0150 = c0150;
	}

	@Column(name = "C0151", precision = 4)
	public BigDecimal getC0151() {
		return this.c0151;
	}

	public void setC0151(BigDecimal c0151) {
		this.c0151 = c0151;
	}

	@Column(name = "C0152", precision = 4)
	public BigDecimal getC0152() {
		return this.c0152;
	}

	public void setC0152(BigDecimal c0152) {
		this.c0152 = c0152;
	}

	@Column(name = "C0153", precision = 4)
	public BigDecimal getC0153() {
		return this.c0153;
	}

	public void setC0153(BigDecimal c0153) {
		this.c0153 = c0153;
	}

	@Column(name = "C0154", precision = 4)
	public BigDecimal getC0154() {
		return this.c0154;
	}

	public void setC0154(BigDecimal c0154) {
		this.c0154 = c0154;
	}

	@Column(name = "C0155", precision = 4)
	public BigDecimal getC0155() {
		return this.c0155;
	}

	public void setC0155(BigDecimal c0155) {
		this.c0155 = c0155;
	}

	@Column(name = "C0156", precision = 7)
	public BigDecimal getC0156() {
		return this.c0156;
	}

	public void setC0156(BigDecimal c0156) {
		this.c0156 = c0156;
	}

	@Column(name = "C0157", precision = 4)
	public BigDecimal getC0157() {
		return this.c0157;
	}

	public void setC0157(BigDecimal c0157) {
		this.c0157 = c0157;
	}

	@Column(name = "C0158", precision = 4)
	public BigDecimal getC0158() {
		return this.c0158;
	}

	public void setC0158(BigDecimal c0158) {
		this.c0158 = c0158;
	}

	@Column(name = "C0159", precision = 4)
	public BigDecimal getC0159() {
		return this.c0159;
	}

	public void setC0159(BigDecimal c0159) {
		this.c0159 = c0159;
	}

	@Column(name = "C0160", precision = 4)
	public BigDecimal getC0160() {
		return this.c0160;
	}

	public void setC0160(BigDecimal c0160) {
		this.c0160 = c0160;
	}

	@Column(name = "C0161", precision = 4)
	public BigDecimal getC0161() {
		return this.c0161;
	}

	public void setC0161(BigDecimal c0161) {
		this.c0161 = c0161;
	}

	@Column(name = "C0162", precision = 4)
	public BigDecimal getC0162() {
		return this.c0162;
	}

	public void setC0162(BigDecimal c0162) {
		this.c0162 = c0162;
	}

	@Column(name = "C0163", precision = 4)
	public BigDecimal getC0163() {
		return this.c0163;
	}

	public void setC0163(BigDecimal c0163) {
		this.c0163 = c0163;
	}

	@Column(name = "C0164", precision = 4)
	public BigDecimal getC0164() {
		return this.c0164;
	}

	public void setC0164(BigDecimal c0164) {
		this.c0164 = c0164;
	}

	@Column(name = "C0165", precision = 7)
	public BigDecimal getC0165() {
		return this.c0165;
	}

	public void setC0165(BigDecimal c0165) {
		this.c0165 = c0165;
	}

	@Column(name = "C0166", precision = 7)
	public BigDecimal getC0166() {
		return this.c0166;
	}

	public void setC0166(BigDecimal c0166) {
		this.c0166 = c0166;
	}

	@Column(name = "C0167", precision = 4)
	public BigDecimal getC0167() {
		return this.c0167;
	}

	public void setC0167(BigDecimal c0167) {
		this.c0167 = c0167;
	}

	@Column(name = "C0168", precision = 1, scale = 0)
	public Boolean getC0168() {
		return this.c0168;
	}

	public void setC0168(Boolean c0168) {
		this.c0168 = c0168;
	}

	@Column(name = "C0169", precision = 3, scale = 0)
	public Short getC0169() {
		return this.c0169;
	}

	public void setC0169(Short c0169) {
		this.c0169 = c0169;
	}

	@Column(name = "C0170", precision = 2, scale = 0)
	public Byte getC0170() {
		return this.c0170;
	}

	public void setC0170(Byte c0170) {
		this.c0170 = c0170;
	}

	@Column(name = "C0171", precision = 2, scale = 0)
	public Byte getC0171() {
		return this.c0171;
	}

	public void setC0171(Byte c0171) {
		this.c0171 = c0171;
	}

	@Column(name = "C0172", precision = 2, scale = 0)
	public Byte getC0172() {
		return this.c0172;
	}

	public void setC0172(Byte c0172) {
		this.c0172 = c0172;
	}

	@Column(name = "C0173", precision = 2, scale = 0)
	public Byte getC0173() {
		return this.c0173;
	}

	public void setC0173(Byte c0173) {
		this.c0173 = c0173;
	}

	@Column(name = "C0174", precision = 2, scale = 0)
	public Byte getC0174() {
		return this.c0174;
	}

	public void setC0174(Byte c0174) {
		this.c0174 = c0174;
	}

	@Column(name = "C0175", precision = 2, scale = 0)
	public Byte getC0175() {
		return this.c0175;
	}

	public void setC0175(Byte c0175) {
		this.c0175 = c0175;
	}

	@Column(name = "C0176", precision = 2, scale = 0)
	public Byte getC0176() {
		return this.c0176;
	}

	public void setC0176(Byte c0176) {
		this.c0176 = c0176;
	}

	@Column(name = "C0177", precision = 2, scale = 0)
	public Byte getC0177() {
		return this.c0177;
	}

	public void setC0177(Byte c0177) {
		this.c0177 = c0177;
	}

	@Column(name = "C0178", precision = 2, scale = 0)
	public Byte getC0178() {
		return this.c0178;
	}

	public void setC0178(Byte c0178) {
		this.c0178 = c0178;
	}

	@Column(name = "C0179", precision = 1, scale = 0)
	public Boolean getC0179() {
		return this.c0179;
	}

	public void setC0179(Boolean c0179) {
		this.c0179 = c0179;
	}

	@Column(name = "C0180", length = 38)
	public String getC0180() {
		return this.c0180;
	}

	public void setC0180(String c0180) {
		this.c0180 = c0180;
	}

	@Column(name = "C0181", length = 16)
	public String getC0181() {
		return this.c0181;
	}

	public void setC0181(String c0181) {
		this.c0181 = c0181;
	}

	@Column(name = "C0182", length = 8)
	public String getC0182() {
		return this.c0182;
	}

	public void setC0182(String c0182) {
		this.c0182 = c0182;
	}

	@Column(name = "C0183", precision = 12, scale = 0)
	public Long getC0183() {
		return this.c0183;
	}

	public void setC0183(Long c0183) {
		this.c0183 = c0183;
	}

	@Column(name = "C0184", length = 34)
	public String getC0184() {
		return this.c0184;
	}

	public void setC0184(String c0184) {
		this.c0184 = c0184;
	}

	@Column(name = "C0185", length = 12)
	public String getC0185() {
		return this.c0185;
	}

	public void setC0185(String c0185) {
		this.c0185 = c0185;
	}

	@Column(name = "C0186", precision = 4, scale = 0)
	public Short getC0186() {
		return this.c0186;
	}

	public void setC0186(Short c0186) {
		this.c0186 = c0186;
	}

	@Column(name = "C0187", precision = 4, scale = 0)
	public Short getC0187() {
		return this.c0187;
	}

	public void setC0187(Short c0187) {
		this.c0187 = c0187;
	}

	@Column(name = "C0188", precision = 1, scale = 0)
	public Boolean getC0188() {
		return this.c0188;
	}

	public void setC0188(Boolean c0188) {
		this.c0188 = c0188;
	}

	@Column(name = "C0189", precision = 1, scale = 0)
	public Boolean getC0189() {
		return this.c0189;
	}

	public void setC0189(Boolean c0189) {
		this.c0189 = c0189;
	}

	@Column(name = "C0190", length = 12)
	public String getC0190() {
		return this.c0190;
	}

	public void setC0190(String c0190) {
		this.c0190 = c0190;
	}

	@Column(name = "C0191", length = 12)
	public String getC0191() {
		return this.c0191;
	}

	public void setC0191(String c0191) {
		this.c0191 = c0191;
	}

	@Column(name = "C01DM", length = 16)
	public String getC01dm() {
		return this.c01dm;
	}

	public void setC01dm(String c01dm) {
		this.c01dm = c01dm;
	}

}
