package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pe00 generated by hbm2java
 */
@Entity
@Table(name = "PE00", schema = "DB2ADMIN")
public class Pe00 implements java.io.Serializable {

	private byte e0001;
	private Integer e0002;
	private Integer e0003;
	private Integer e0004;
	private Integer e0005;
	private Short e0006;
	private Short e0007;
	private Short e0008;
	private Integer e0009;
	private Integer e0010;
	private Integer e0011;
	private Integer e0012;
	private Integer e0013;
	private Integer e0014;
	private Integer e0015;
	private Integer e0016;
	private Integer e0017;
	private String e00dm;

	public Pe00() {
	}

	public Pe00(byte e0001) {
		this.e0001 = e0001;
	}

	public Pe00(byte e0001, Integer e0002, Integer e0003, Integer e0004,
			Integer e0005, Short e0006, Short e0007, Short e0008,
			Integer e0009, Integer e0010, Integer e0011, Integer e0012,
			Integer e0013, Integer e0014, Integer e0015, Integer e0016,
			Integer e0017, String e00dm) {
		this.e0001 = e0001;
		this.e0002 = e0002;
		this.e0003 = e0003;
		this.e0004 = e0004;
		this.e0005 = e0005;
		this.e0006 = e0006;
		this.e0007 = e0007;
		this.e0008 = e0008;
		this.e0009 = e0009;
		this.e0010 = e0010;
		this.e0011 = e0011;
		this.e0012 = e0012;
		this.e0013 = e0013;
		this.e0014 = e0014;
		this.e0015 = e0015;
		this.e0016 = e0016;
		this.e0017 = e0017;
		this.e00dm = e00dm;
	}

	@Id
	@Column(name = "E0001", unique = true, nullable = false, precision = 2, scale = 0)
	public byte getE0001() {
		return this.e0001;
	}

	public void setE0001(byte e0001) {
		this.e0001 = e0001;
	}

	@Column(name = "E0002", precision = 6, scale = 0)
	public Integer getE0002() {
		return this.e0002;
	}

	public void setE0002(Integer e0002) {
		this.e0002 = e0002;
	}

	@Column(name = "E0003", precision = 6, scale = 0)
	public Integer getE0003() {
		return this.e0003;
	}

	public void setE0003(Integer e0003) {
		this.e0003 = e0003;
	}

	@Column(name = "E0004", precision = 6, scale = 0)
	public Integer getE0004() {
		return this.e0004;
	}

	public void setE0004(Integer e0004) {
		this.e0004 = e0004;
	}

	@Column(name = "E0005", precision = 6, scale = 0)
	public Integer getE0005() {
		return this.e0005;
	}

	public void setE0005(Integer e0005) {
		this.e0005 = e0005;
	}

	@Column(name = "E0006", precision = 4, scale = 0)
	public Short getE0006() {
		return this.e0006;
	}

	public void setE0006(Short e0006) {
		this.e0006 = e0006;
	}

	@Column(name = "E0007", precision = 4, scale = 0)
	public Short getE0007() {
		return this.e0007;
	}

	public void setE0007(Short e0007) {
		this.e0007 = e0007;
	}

	@Column(name = "E0008", precision = 4, scale = 0)
	public Short getE0008() {
		return this.e0008;
	}

	public void setE0008(Short e0008) {
		this.e0008 = e0008;
	}

	@Column(name = "E0009", precision = 8, scale = 0)
	public Integer getE0009() {
		return this.e0009;
	}

	public void setE0009(Integer e0009) {
		this.e0009 = e0009;
	}

	@Column(name = "E0010", precision = 8, scale = 0)
	public Integer getE0010() {
		return this.e0010;
	}

	public void setE0010(Integer e0010) {
		this.e0010 = e0010;
	}

	@Column(name = "E0011", precision = 8, scale = 0)
	public Integer getE0011() {
		return this.e0011;
	}

	public void setE0011(Integer e0011) {
		this.e0011 = e0011;
	}

	@Column(name = "E0012", precision = 8, scale = 0)
	public Integer getE0012() {
		return this.e0012;
	}

	public void setE0012(Integer e0012) {
		this.e0012 = e0012;
	}

	@Column(name = "E0013", precision = 8, scale = 0)
	public Integer getE0013() {
		return this.e0013;
	}

	public void setE0013(Integer e0013) {
		this.e0013 = e0013;
	}

	@Column(name = "E0014", precision = 8, scale = 0)
	public Integer getE0014() {
		return this.e0014;
	}

	public void setE0014(Integer e0014) {
		this.e0014 = e0014;
	}

	@Column(name = "E0015", precision = 8, scale = 0)
	public Integer getE0015() {
		return this.e0015;
	}

	public void setE0015(Integer e0015) {
		this.e0015 = e0015;
	}

	@Column(name = "E0016", precision = 7, scale = 0)
	public Integer getE0016() {
		return this.e0016;
	}

	public void setE0016(Integer e0016) {
		this.e0016 = e0016;
	}

	@Column(name = "E0017", precision = 8, scale = 0)
	public Integer getE0017() {
		return this.e0017;
	}

	public void setE0017(Integer e0017) {
		this.e0017 = e0017;
	}

	@Column(name = "E00DM", length = 11)
	public String getE00dm() {
		return this.e00dm;
	}

	public void setE00dm(String e00dm) {
		this.e00dm = e00dm;
	}

}
