package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pe03 generated by hbm2java
 */
@Entity
@Table(name = "PE03", schema = "DB2ADMIN")
public class Pe03 implements java.io.Serializable {

	private short e0301;
	private String e0302;
	private String e0303;
	private String e0304;
	private String e0305;
	private Long e0306;
	private String e0307;
	private Boolean e0308;
	private Byte e0309;
	private Boolean e0310;
	private Integer e0311;
	private Integer e0312;
	private Integer e0313;
	private Integer e0314;
	private Integer e0315;
	private Integer e0316;
	private Integer e0317;
	private Integer e0318;
	private Integer e0319;
	private Integer e0320;
	private Integer e0321;
	private Integer e0322;
	private Integer e0323;
	private Integer e0324;
	private Integer e0325;
	private Integer e0326;
	private Integer e0327;
	private Integer e0328;
	private Integer e0329;
	private Integer e0330;
	private Integer e0331;
	private Integer e0332;
	private Integer e0333;
	private Integer e0334;
	private Integer e0335;
	private Integer e0336;
	private Integer e0337;
	private Integer e0338;
	private Integer e0339;
	private Integer e0340;
	private Integer e0341;
	private Integer e0342;
	private Integer e0343;
	private Integer e0344;
	private Integer e0345;
	private Integer e0346;
	private Short e0347;
	private Integer e0348;
	private Integer e0349;
	private Integer e0350;
	private Integer e0351;
	private Integer e0352;
	private Integer e0353;
	private Integer e0354;
	private Integer e0355;
	private Integer e0356;
	private String e0357;
	private String e03dm;

	public Pe03() {
	}

	public Pe03(short e0301) {
		this.e0301 = e0301;
	}

	public Pe03(short e0301, String e0302, String e0303, String e0304,
			String e0305, Long e0306, String e0307, Boolean e0308, Byte e0309,
			Boolean e0310, Integer e0311, Integer e0312, Integer e0313,
			Integer e0314, Integer e0315, Integer e0316, Integer e0317,
			Integer e0318, Integer e0319, Integer e0320, Integer e0321,
			Integer e0322, Integer e0323, Integer e0324, Integer e0325,
			Integer e0326, Integer e0327, Integer e0328, Integer e0329,
			Integer e0330, Integer e0331, Integer e0332, Integer e0333,
			Integer e0334, Integer e0335, Integer e0336, Integer e0337,
			Integer e0338, Integer e0339, Integer e0340, Integer e0341,
			Integer e0342, Integer e0343, Integer e0344, Integer e0345,
			Integer e0346, Short e0347, Integer e0348, Integer e0349,
			Integer e0350, Integer e0351, Integer e0352, Integer e0353,
			Integer e0354, Integer e0355, Integer e0356, String e0357,
			String e03dm) {
		this.e0301 = e0301;
		this.e0302 = e0302;
		this.e0303 = e0303;
		this.e0304 = e0304;
		this.e0305 = e0305;
		this.e0306 = e0306;
		this.e0307 = e0307;
		this.e0308 = e0308;
		this.e0309 = e0309;
		this.e0310 = e0310;
		this.e0311 = e0311;
		this.e0312 = e0312;
		this.e0313 = e0313;
		this.e0314 = e0314;
		this.e0315 = e0315;
		this.e0316 = e0316;
		this.e0317 = e0317;
		this.e0318 = e0318;
		this.e0319 = e0319;
		this.e0320 = e0320;
		this.e0321 = e0321;
		this.e0322 = e0322;
		this.e0323 = e0323;
		this.e0324 = e0324;
		this.e0325 = e0325;
		this.e0326 = e0326;
		this.e0327 = e0327;
		this.e0328 = e0328;
		this.e0329 = e0329;
		this.e0330 = e0330;
		this.e0331 = e0331;
		this.e0332 = e0332;
		this.e0333 = e0333;
		this.e0334 = e0334;
		this.e0335 = e0335;
		this.e0336 = e0336;
		this.e0337 = e0337;
		this.e0338 = e0338;
		this.e0339 = e0339;
		this.e0340 = e0340;
		this.e0341 = e0341;
		this.e0342 = e0342;
		this.e0343 = e0343;
		this.e0344 = e0344;
		this.e0345 = e0345;
		this.e0346 = e0346;
		this.e0347 = e0347;
		this.e0348 = e0348;
		this.e0349 = e0349;
		this.e0350 = e0350;
		this.e0351 = e0351;
		this.e0352 = e0352;
		this.e0353 = e0353;
		this.e0354 = e0354;
		this.e0355 = e0355;
		this.e0356 = e0356;
		this.e0357 = e0357;
		this.e03dm = e03dm;
	}

	@Id
	@Column(name = "E0301", unique = true, nullable = false, precision = 4, scale = 0)
	public short getE0301() {
		return this.e0301;
	}

	public void setE0301(short e0301) {
		this.e0301 = e0301;
	}

	@Column(name = "E0302", length = 32)
	public String getE0302() {
		return this.e0302;
	}

	public void setE0302(String e0302) {
		this.e0302 = e0302;
	}

	@Column(name = "E0303", length = 32)
	public String getE0303() {
		return this.e0303;
	}

	public void setE0303(String e0303) {
		this.e0303 = e0303;
	}

	@Column(name = "E0304", length = 30)
	public String getE0304() {
		return this.e0304;
	}

	public void setE0304(String e0304) {
		this.e0304 = e0304;
	}

	@Column(name = "E0305", length = 8)
	public String getE0305() {
		return this.e0305;
	}

	public void setE0305(String e0305) {
		this.e0305 = e0305;
	}

	@Column(name = "E0306", precision = 12, scale = 0)
	public Long getE0306() {
		return this.e0306;
	}

	public void setE0306(Long e0306) {
		this.e0306 = e0306;
	}

	@Column(name = "E0307", length = 34)
	public String getE0307() {
		return this.e0307;
	}

	public void setE0307(String e0307) {
		this.e0307 = e0307;
	}

	@Column(name = "E0308", precision = 1, scale = 0)
	public Boolean getE0308() {
		return this.e0308;
	}

	public void setE0308(Boolean e0308) {
		this.e0308 = e0308;
	}

	@Column(name = "E0309", precision = 2, scale = 0)
	public Byte getE0309() {
		return this.e0309;
	}

	public void setE0309(Byte e0309) {
		this.e0309 = e0309;
	}

	@Column(name = "E0310", precision = 1, scale = 0)
	public Boolean getE0310() {
		return this.e0310;
	}

	public void setE0310(Boolean e0310) {
		this.e0310 = e0310;
	}

	@Column(name = "E0311", precision = 8, scale = 0)
	public Integer getE0311() {
		return this.e0311;
	}

	public void setE0311(Integer e0311) {
		this.e0311 = e0311;
	}

	@Column(name = "E0312", precision = 8, scale = 0)
	public Integer getE0312() {
		return this.e0312;
	}

	public void setE0312(Integer e0312) {
		this.e0312 = e0312;
	}

	@Column(name = "E0313", precision = 8, scale = 0)
	public Integer getE0313() {
		return this.e0313;
	}

	public void setE0313(Integer e0313) {
		this.e0313 = e0313;
	}

	@Column(name = "E0314", precision = 8, scale = 0)
	public Integer getE0314() {
		return this.e0314;
	}

	public void setE0314(Integer e0314) {
		this.e0314 = e0314;
	}

	@Column(name = "E0315", precision = 8, scale = 0)
	public Integer getE0315() {
		return this.e0315;
	}

	public void setE0315(Integer e0315) {
		this.e0315 = e0315;
	}

	@Column(name = "E0316", precision = 8, scale = 0)
	public Integer getE0316() {
		return this.e0316;
	}

	public void setE0316(Integer e0316) {
		this.e0316 = e0316;
	}

	@Column(name = "E0317", precision = 8, scale = 0)
	public Integer getE0317() {
		return this.e0317;
	}

	public void setE0317(Integer e0317) {
		this.e0317 = e0317;
	}

	@Column(name = "E0318", precision = 8, scale = 0)
	public Integer getE0318() {
		return this.e0318;
	}

	public void setE0318(Integer e0318) {
		this.e0318 = e0318;
	}

	@Column(name = "E0319", precision = 8, scale = 0)
	public Integer getE0319() {
		return this.e0319;
	}

	public void setE0319(Integer e0319) {
		this.e0319 = e0319;
	}

	@Column(name = "E0320", precision = 8, scale = 0)
	public Integer getE0320() {
		return this.e0320;
	}

	public void setE0320(Integer e0320) {
		this.e0320 = e0320;
	}

	@Column(name = "E0321", precision = 8, scale = 0)
	public Integer getE0321() {
		return this.e0321;
	}

	public void setE0321(Integer e0321) {
		this.e0321 = e0321;
	}

	@Column(name = "E0322", precision = 8, scale = 0)
	public Integer getE0322() {
		return this.e0322;
	}

	public void setE0322(Integer e0322) {
		this.e0322 = e0322;
	}

	@Column(name = "E0323", precision = 8, scale = 0)
	public Integer getE0323() {
		return this.e0323;
	}

	public void setE0323(Integer e0323) {
		this.e0323 = e0323;
	}

	@Column(name = "E0324", precision = 8, scale = 0)
	public Integer getE0324() {
		return this.e0324;
	}

	public void setE0324(Integer e0324) {
		this.e0324 = e0324;
	}

	@Column(name = "E0325", precision = 8, scale = 0)
	public Integer getE0325() {
		return this.e0325;
	}

	public void setE0325(Integer e0325) {
		this.e0325 = e0325;
	}

	@Column(name = "E0326", precision = 8, scale = 0)
	public Integer getE0326() {
		return this.e0326;
	}

	public void setE0326(Integer e0326) {
		this.e0326 = e0326;
	}

	@Column(name = "E0327", precision = 8, scale = 0)
	public Integer getE0327() {
		return this.e0327;
	}

	public void setE0327(Integer e0327) {
		this.e0327 = e0327;
	}

	@Column(name = "E0328", precision = 8, scale = 0)
	public Integer getE0328() {
		return this.e0328;
	}

	public void setE0328(Integer e0328) {
		this.e0328 = e0328;
	}

	@Column(name = "E0329", precision = 8, scale = 0)
	public Integer getE0329() {
		return this.e0329;
	}

	public void setE0329(Integer e0329) {
		this.e0329 = e0329;
	}

	@Column(name = "E0330", precision = 8, scale = 0)
	public Integer getE0330() {
		return this.e0330;
	}

	public void setE0330(Integer e0330) {
		this.e0330 = e0330;
	}

	@Column(name = "E0331", precision = 8, scale = 0)
	public Integer getE0331() {
		return this.e0331;
	}

	public void setE0331(Integer e0331) {
		this.e0331 = e0331;
	}

	@Column(name = "E0332", precision = 8, scale = 0)
	public Integer getE0332() {
		return this.e0332;
	}

	public void setE0332(Integer e0332) {
		this.e0332 = e0332;
	}

	@Column(name = "E0333", precision = 8, scale = 0)
	public Integer getE0333() {
		return this.e0333;
	}

	public void setE0333(Integer e0333) {
		this.e0333 = e0333;
	}

	@Column(name = "E0334", precision = 8, scale = 0)
	public Integer getE0334() {
		return this.e0334;
	}

	public void setE0334(Integer e0334) {
		this.e0334 = e0334;
	}

	@Column(name = "E0335", precision = 8, scale = 0)
	public Integer getE0335() {
		return this.e0335;
	}

	public void setE0335(Integer e0335) {
		this.e0335 = e0335;
	}

	@Column(name = "E0336", precision = 8, scale = 0)
	public Integer getE0336() {
		return this.e0336;
	}

	public void setE0336(Integer e0336) {
		this.e0336 = e0336;
	}

	@Column(name = "E0337", precision = 8, scale = 0)
	public Integer getE0337() {
		return this.e0337;
	}

	public void setE0337(Integer e0337) {
		this.e0337 = e0337;
	}

	@Column(name = "E0338", precision = 8, scale = 0)
	public Integer getE0338() {
		return this.e0338;
	}

	public void setE0338(Integer e0338) {
		this.e0338 = e0338;
	}

	@Column(name = "E0339", precision = 8, scale = 0)
	public Integer getE0339() {
		return this.e0339;
	}

	public void setE0339(Integer e0339) {
		this.e0339 = e0339;
	}

	@Column(name = "E0340", precision = 8, scale = 0)
	public Integer getE0340() {
		return this.e0340;
	}

	public void setE0340(Integer e0340) {
		this.e0340 = e0340;
	}

	@Column(name = "E0341", precision = 8, scale = 0)
	public Integer getE0341() {
		return this.e0341;
	}

	public void setE0341(Integer e0341) {
		this.e0341 = e0341;
	}

	@Column(name = "E0342", precision = 8, scale = 0)
	public Integer getE0342() {
		return this.e0342;
	}

	public void setE0342(Integer e0342) {
		this.e0342 = e0342;
	}

	@Column(name = "E0343", precision = 8, scale = 0)
	public Integer getE0343() {
		return this.e0343;
	}

	public void setE0343(Integer e0343) {
		this.e0343 = e0343;
	}

	@Column(name = "E0344", precision = 8, scale = 0)
	public Integer getE0344() {
		return this.e0344;
	}

	public void setE0344(Integer e0344) {
		this.e0344 = e0344;
	}

	@Column(name = "E0345", precision = 8, scale = 0)
	public Integer getE0345() {
		return this.e0345;
	}

	public void setE0345(Integer e0345) {
		this.e0345 = e0345;
	}

	@Column(name = "E0346", precision = 8, scale = 0)
	public Integer getE0346() {
		return this.e0346;
	}

	public void setE0346(Integer e0346) {
		this.e0346 = e0346;
	}

	@Column(name = "E0347", precision = 4, scale = 0)
	public Short getE0347() {
		return this.e0347;
	}

	public void setE0347(Short e0347) {
		this.e0347 = e0347;
	}

	@Column(name = "E0348", precision = 7, scale = 0)
	public Integer getE0348() {
		return this.e0348;
	}

	public void setE0348(Integer e0348) {
		this.e0348 = e0348;
	}

	@Column(name = "E0349", precision = 7, scale = 0)
	public Integer getE0349() {
		return this.e0349;
	}

	public void setE0349(Integer e0349) {
		this.e0349 = e0349;
	}

	@Column(name = "E0350", precision = 7, scale = 0)
	public Integer getE0350() {
		return this.e0350;
	}

	public void setE0350(Integer e0350) {
		this.e0350 = e0350;
	}

	@Column(name = "E0351", precision = 7, scale = 0)
	public Integer getE0351() {
		return this.e0351;
	}

	public void setE0351(Integer e0351) {
		this.e0351 = e0351;
	}

	@Column(name = "E0352", precision = 7, scale = 0)
	public Integer getE0352() {
		return this.e0352;
	}

	public void setE0352(Integer e0352) {
		this.e0352 = e0352;
	}

	@Column(name = "E0353", precision = 7, scale = 0)
	public Integer getE0353() {
		return this.e0353;
	}

	public void setE0353(Integer e0353) {
		this.e0353 = e0353;
	}

	@Column(name = "E0354", precision = 7, scale = 0)
	public Integer getE0354() {
		return this.e0354;
	}

	public void setE0354(Integer e0354) {
		this.e0354 = e0354;
	}

	@Column(name = "E0355", precision = 7, scale = 0)
	public Integer getE0355() {
		return this.e0355;
	}

	public void setE0355(Integer e0355) {
		this.e0355 = e0355;
	}

	@Column(name = "E0356", precision = 7, scale = 0)
	public Integer getE0356() {
		return this.e0356;
	}

	public void setE0356(Integer e0356) {
		this.e0356 = e0356;
	}

	@Column(name = "E0357", length = 2)
	public String getE0357() {
		return this.e0357;
	}

	public void setE0357(String e0357) {
		this.e0357 = e0357;
	}

	@Column(name = "E03DM", length = 19)
	public String getE03dm() {
		return this.e03dm;
	}

	public void setE03dm(String e03dm) {
		this.e03dm = e03dm;
	}

}
