package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Pe04Id generated by hbm2java
 */
@Embeddable
public class Pe04Id implements java.io.Serializable {

	private short e0401;
	private String e0402;

	public Pe04Id() {
	}

	public Pe04Id(short e0401, String e0402) {
		this.e0401 = e0401;
		this.e0402 = e0402;
	}

	@Column(name = "E0401", nullable = false, precision = 3, scale = 0)
	public short getE0401() {
		return this.e0401;
	}

	public void setE0401(short e0401) {
		this.e0401 = e0401;
	}

	@Column(name = "E0402", nullable = false, length = 4)
	public String getE0402() {
		return this.e0402;
	}

	public void setE0402(String e0402) {
		this.e0402 = e0402;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Pe04Id))
			return false;
		Pe04Id castOther = (Pe04Id) other;

		return (this.getE0401() == castOther.getE0401())
				&& ((this.getE0402() == castOther.getE0402()) || (this
						.getE0402() != null && castOther.getE0402() != null && this
						.getE0402().equals(castOther.getE0402())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getE0401();
		result = 37 * result
				+ (getE0402() == null ? 0 : this.getE0402().hashCode());
		return result;
	}

}
