package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pe04 generated by hbm2java
 */
@Entity
@Table(name = "PE04", schema = "DB2ADMIN")
public class Pe04 implements java.io.Serializable {

	private Pe04Id id;
	private Character e0403;
	private String e0404;
	private String e0405;
	private Short e0406;
	private String e0407;
	private Integer e0408;
	private Integer e0409;
	private Integer e0410;
	private Integer e0411;
	private Integer e0412;
	private Integer e0413;
	private Integer e0414;
	private Integer e0415;
	private Integer e0416;
	private Integer e0417;
	private Integer e0418;
	private Integer e0419;
	private Integer e0420;
	private Integer e0421;
	private Integer e0422;
	private Integer e0423;
	private Integer e0424;
	private String e04dm;

	public Pe04() {
	}

	public Pe04(Pe04Id id) {
		this.id = id;
	}

	public Pe04(Pe04Id id, Character e0403, String e0404, String e0405,
			Short e0406, String e0407, Integer e0408, Integer e0409,
			Integer e0410, Integer e0411, Integer e0412, Integer e0413,
			Integer e0414, Integer e0415, Integer e0416, Integer e0417,
			Integer e0418, Integer e0419, Integer e0420, Integer e0421,
			Integer e0422, Integer e0423, Integer e0424, String e04dm) {
		this.id = id;
		this.e0403 = e0403;
		this.e0404 = e0404;
		this.e0405 = e0405;
		this.e0406 = e0406;
		this.e0407 = e0407;
		this.e0408 = e0408;
		this.e0409 = e0409;
		this.e0410 = e0410;
		this.e0411 = e0411;
		this.e0412 = e0412;
		this.e0413 = e0413;
		this.e0414 = e0414;
		this.e0415 = e0415;
		this.e0416 = e0416;
		this.e0417 = e0417;
		this.e0418 = e0418;
		this.e0419 = e0419;
		this.e0420 = e0420;
		this.e0421 = e0421;
		this.e0422 = e0422;
		this.e0423 = e0423;
		this.e0424 = e0424;
		this.e04dm = e04dm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "e0401", column = @Column(name = "E0401", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "e0402", column = @Column(name = "E0402", nullable = false, length = 4)) })
	public Pe04Id getId() {
		return this.id;
	}

	public void setId(Pe04Id id) {
		this.id = id;
	}

	@Column(name = "E0403", length = 1)
	public Character getE0403() {
		return this.e0403;
	}

	public void setE0403(Character e0403) {
		this.e0403 = e0403;
	}

	@Column(name = "E0404", length = 2)
	public String getE0404() {
		return this.e0404;
	}

	public void setE0404(String e0404) {
		this.e0404 = e0404;
	}

	@Column(name = "E0405", length = 4)
	public String getE0405() {
		return this.e0405;
	}

	public void setE0405(String e0405) {
		this.e0405 = e0405;
	}

	@Column(name = "E0406", precision = 4, scale = 0)
	public Short getE0406() {
		return this.e0406;
	}

	public void setE0406(Short e0406) {
		this.e0406 = e0406;
	}

	@Column(name = "E0407", length = 7)
	public String getE0407() {
		return this.e0407;
	}

	public void setE0407(String e0407) {
		this.e0407 = e0407;
	}

	@Column(name = "E0408", precision = 7, scale = 0)
	public Integer getE0408() {
		return this.e0408;
	}

	public void setE0408(Integer e0408) {
		this.e0408 = e0408;
	}

	@Column(name = "E0409", precision = 7, scale = 0)
	public Integer getE0409() {
		return this.e0409;
	}

	public void setE0409(Integer e0409) {
		this.e0409 = e0409;
	}

	@Column(name = "E0410", precision = 7, scale = 0)
	public Integer getE0410() {
		return this.e0410;
	}

	public void setE0410(Integer e0410) {
		this.e0410 = e0410;
	}

	@Column(name = "E0411", precision = 7, scale = 0)
	public Integer getE0411() {
		return this.e0411;
	}

	public void setE0411(Integer e0411) {
		this.e0411 = e0411;
	}

	@Column(name = "E0412", precision = 7, scale = 0)
	public Integer getE0412() {
		return this.e0412;
	}

	public void setE0412(Integer e0412) {
		this.e0412 = e0412;
	}

	@Column(name = "E0413", precision = 7, scale = 0)
	public Integer getE0413() {
		return this.e0413;
	}

	public void setE0413(Integer e0413) {
		this.e0413 = e0413;
	}

	@Column(name = "E0414", precision = 7, scale = 0)
	public Integer getE0414() {
		return this.e0414;
	}

	public void setE0414(Integer e0414) {
		this.e0414 = e0414;
	}

	@Column(name = "E0415", precision = 7, scale = 0)
	public Integer getE0415() {
		return this.e0415;
	}

	public void setE0415(Integer e0415) {
		this.e0415 = e0415;
	}

	@Column(name = "E0416", precision = 7, scale = 0)
	public Integer getE0416() {
		return this.e0416;
	}

	public void setE0416(Integer e0416) {
		this.e0416 = e0416;
	}

	@Column(name = "E0417", precision = 7, scale = 0)
	public Integer getE0417() {
		return this.e0417;
	}

	public void setE0417(Integer e0417) {
		this.e0417 = e0417;
	}

	@Column(name = "E0418", precision = 7, scale = 0)
	public Integer getE0418() {
		return this.e0418;
	}

	public void setE0418(Integer e0418) {
		this.e0418 = e0418;
	}

	@Column(name = "E0419", precision = 7, scale = 0)
	public Integer getE0419() {
		return this.e0419;
	}

	public void setE0419(Integer e0419) {
		this.e0419 = e0419;
	}

	@Column(name = "E0420", precision = 7, scale = 0)
	public Integer getE0420() {
		return this.e0420;
	}

	public void setE0420(Integer e0420) {
		this.e0420 = e0420;
	}

	@Column(name = "E0421", precision = 7, scale = 0)
	public Integer getE0421() {
		return this.e0421;
	}

	public void setE0421(Integer e0421) {
		this.e0421 = e0421;
	}

	@Column(name = "E0422", precision = 7, scale = 0)
	public Integer getE0422() {
		return this.e0422;
	}

	public void setE0422(Integer e0422) {
		this.e0422 = e0422;
	}

	@Column(name = "E0423", precision = 8, scale = 0)
	public Integer getE0423() {
		return this.e0423;
	}

	public void setE0423(Integer e0423) {
		this.e0423 = e0423;
	}

	@Column(name = "E0424", precision = 8, scale = 0)
	public Integer getE0424() {
		return this.e0424;
	}

	public void setE0424(Integer e0424) {
		this.e0424 = e0424;
	}

	@Column(name = "E04DM", length = 18)
	public String getE04dm() {
		return this.e04dm;
	}

	public void setE04dm(String e04dm) {
		this.e04dm = e04dm;
	}

}
