package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pe07 generated by hbm2java
 */
@Entity
@Table(name = "PE07", schema = "DB2ADMIN")
public class Pe07 implements java.io.Serializable {

	private Pe07Id id;
	private Boolean e0703;
	private Integer e0704;
	private Short e0705;
	private Short e0706;
	private Short e0707;
	private Short e0708;
	private Integer e0709;
	private BigDecimal e0710;
	private Integer e0711;
	private Integer e0712;
	private String e0713;
	private Boolean e0714;
	private String e0715;
	private Boolean e0716;
	private Integer e0717;
	private Integer e0718;
	private Integer e0719;
	private String e07dm;

	public Pe07() {
	}

	public Pe07(Pe07Id id) {
		this.id = id;
	}

	public Pe07(Pe07Id id, Boolean e0703, Integer e0704, Short e0705,
			Short e0706, Short e0707, Short e0708, Integer e0709,
			BigDecimal e0710, Integer e0711, Integer e0712, String e0713,
			Boolean e0714, String e0715, Boolean e0716, Integer e0717,
			Integer e0718, Integer e0719, String e07dm) {
		this.id = id;
		this.e0703 = e0703;
		this.e0704 = e0704;
		this.e0705 = e0705;
		this.e0706 = e0706;
		this.e0707 = e0707;
		this.e0708 = e0708;
		this.e0709 = e0709;
		this.e0710 = e0710;
		this.e0711 = e0711;
		this.e0712 = e0712;
		this.e0713 = e0713;
		this.e0714 = e0714;
		this.e0715 = e0715;
		this.e0716 = e0716;
		this.e0717 = e0717;
		this.e0718 = e0718;
		this.e0719 = e0719;
		this.e07dm = e07dm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "e0701", column = @Column(name = "E0701", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "e0702", column = @Column(name = "E0702", nullable = false, precision = 2, scale = 0)) })
	public Pe07Id getId() {
		return this.id;
	}

	public void setId(Pe07Id id) {
		this.id = id;
	}

	@Column(name = "E0703", precision = 1, scale = 0)
	public Boolean getE0703() {
		return this.e0703;
	}

	public void setE0703(Boolean e0703) {
		this.e0703 = e0703;
	}

	@Column(name = "E0704", precision = 6, scale = 0)
	public Integer getE0704() {
		return this.e0704;
	}

	public void setE0704(Integer e0704) {
		this.e0704 = e0704;
	}

	@Column(name = "E0705", precision = 3, scale = 0)
	public Short getE0705() {
		return this.e0705;
	}

	public void setE0705(Short e0705) {
		this.e0705 = e0705;
	}

	@Column(name = "E0706", precision = 4, scale = 0)
	public Short getE0706() {
		return this.e0706;
	}

	public void setE0706(Short e0706) {
		this.e0706 = e0706;
	}

	@Column(name = "E0707", precision = 3, scale = 0)
	public Short getE0707() {
		return this.e0707;
	}

	public void setE0707(Short e0707) {
		this.e0707 = e0707;
	}

	@Column(name = "E0708", precision = 4, scale = 0)
	public Short getE0708() {
		return this.e0708;
	}

	public void setE0708(Short e0708) {
		this.e0708 = e0708;
	}

	@Column(name = "E0709", precision = 6, scale = 0)
	public Integer getE0709() {
		return this.e0709;
	}

	public void setE0709(Integer e0709) {
		this.e0709 = e0709;
	}

	@Column(name = "E0710", precision = 8)
	public BigDecimal getE0710() {
		return this.e0710;
	}

	public void setE0710(BigDecimal e0710) {
		this.e0710 = e0710;
	}

	@Column(name = "E0711", precision = 6, scale = 0)
	public Integer getE0711() {
		return this.e0711;
	}

	public void setE0711(Integer e0711) {
		this.e0711 = e0711;
	}

	@Column(name = "E0712", precision = 7, scale = 0)
	public Integer getE0712() {
		return this.e0712;
	}

	public void setE0712(Integer e0712) {
		this.e0712 = e0712;
	}

	@Column(name = "E0713", length = 12)
	public String getE0713() {
		return this.e0713;
	}

	public void setE0713(String e0713) {
		this.e0713 = e0713;
	}

	@Column(name = "E0714", precision = 1, scale = 0)
	public Boolean getE0714() {
		return this.e0714;
	}

	public void setE0714(Boolean e0714) {
		this.e0714 = e0714;
	}

	@Column(name = "E0715", length = 2)
	public String getE0715() {
		return this.e0715;
	}

	public void setE0715(String e0715) {
		this.e0715 = e0715;
	}

	@Column(name = "E0716", precision = 1, scale = 0)
	public Boolean getE0716() {
		return this.e0716;
	}

	public void setE0716(Boolean e0716) {
		this.e0716 = e0716;
	}

	@Column(name = "E0717", precision = 5, scale = 0)
	public Integer getE0717() {
		return this.e0717;
	}

	public void setE0717(Integer e0717) {
		this.e0717 = e0717;
	}

	@Column(name = "E0718", precision = 5, scale = 0)
	public Integer getE0718() {
		return this.e0718;
	}

	public void setE0718(Integer e0718) {
		this.e0718 = e0718;
	}

	@Column(name = "E0719", precision = 5, scale = 0)
	public Integer getE0719() {
		return this.e0719;
	}

	public void setE0719(Integer e0719) {
		this.e0719 = e0719;
	}

	@Column(name = "E07DM", length = 17)
	public String getE07dm() {
		return this.e07dm;
	}

	public void setE07dm(String e07dm) {
		this.e07dm = e07dm;
	}

}
