package dao.model;

// Generated Sep 22, 2011 1:42:26 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pg01 generated by hbm2java
 */
@Entity
@Table(name = "PG01", schema = "DB2ADMIN")
public class Pg01 implements java.io.Serializable {

	private String g0101;
	private String g0102;
	private String g0103;
	private String g01dm;

	public Pg01() {
	}

	public Pg01(String g0101) {
		this.g0101 = g0101;
	}

	public Pg01(String g0101, String g0102, String g0103, String g01dm) {
		this.g0101 = g0101;
		this.g0102 = g0102;
		this.g0103 = g0103;
		this.g01dm = g01dm;
	}

	@Id
	@Column(name = "G0101", unique = true, nullable = false, length = 2)
	public String getG0101() {
		return this.g0101;
	}

	public void setG0101(String g0101) {
		this.g0101 = g0101;
	}

	@Column(name = "G0102", length = 8)
	public String getG0102() {
		return this.g0102;
	}

	public void setG0102(String g0102) {
		this.g0102 = g0102;
	}

	@Column(name = "G0103", length = 10)
	public String getG0103() {
		return this.g0103;
	}

	public void setG0103(String g0103) {
		this.g0103 = g0103;
	}

	@Column(name = "G01DM", length = 10)
	public String getG01dm() {
		return this.g01dm;
	}

	public void setG01dm(String g01dm) {
		this.g01dm = g01dm;
	}

}
